---
url: https://developer.rhino3d.com/api/grasshopper/html/4306b177-1bf1-41bc-ac0e-2f6869d02365.htm#SolveInstance
scraped_at: 2025-09-08T16:25:40.609629
title: Untitled
---

Grasshopper API

[Grasshopper API](../html/723c01da-9986-4db2-8f53-6f3a7494df75.htm
"Grasshopper API")

[Examples](../html/d113a9f0-6e27-46df-8316-2079c44382ac.htm "Examples")

[Visual Basic .NET](../html/b883d0c0-4947-48bc-8e9e-492a6d6c2a06.htm "Visual
Basic .NET")

[Simple Component (VB)](../html/b883d0c0-4947-48bc-8e9e-492a6d6c2a06.htm
"Simple Component \(VB\)")

[Simple Mathematics (VB)](../html/2824c770-2673-49a3-8683-1a70bc0349cc.htm
"Simple Mathematics \(VB\)")

[Simple Geometry (VB)](../html/4306b177-1bf1-41bc-ac0e-2f6869d02365.htm
"Simple Geometry \(VB\)")

[Simple Data Types (VB)](../html/f9aa207f-3d19-414c-af01-1e5ad42a8cab.htm
"Simple Data Types \(VB\)")

[Simple Parameters (VB)](../html/0edd8dc9-32a7-40aa-b217-8e01e35e58bc.htm
"Simple Parameters \(VB\)")

[List Component (VB)](../html/4db493ec-0bb3-4b73-943a-fdff03863e1d.htm "List
Component \(VB\)")

[Extending the GUI (VB)](../html/99cd32c8-7c1f-4f9a-87ea-76b032de7f70.htm
"Extending the GUI \(VB\)")

[Custom Attributes (VB)](../html/ad6e93fe-e1c8-451e-a6d0-77cb8dd4516d.htm
"Custom Attributes \(VB\)")

[Custom Component Options
(VB)](../html/434018c0-6110-4478-bf2a-dcd099d8b8b2.htm "Custom Component
Options \(VB\)")

![Click or drag to resize](../icons/TocOpen.gif)![Click or drag to
resize](../icons/TocClose.gif)

# Simple Geometry (VB)  
  
---  
  
  * Introduction
  * Input parameters
  * Output parameters
  * SolveInstance

This article shows how to use some of the simpler geometry types and classes
in the RhinoCommon and Grasshopper SDK. We'll discuss how to deal with
different access levels of input data and invalid Structs vs. invalid and null
Classes. You should have read the [My First
Component](b883d0c0-4947-48bc-8e9e-492a6d6c2a06.htm) and [Simple
Mathematics](2824c770-2673-49a3-8683-1a70bc0349cc.htm) topics before starting
this one.

This component will perform a simple Circle|Line Split operation. We'll
retrieve a single Circle and a single Line input, make sure the data is valid,
project the line onto the circle plane, determine whether or not the Split
operation is valid and then output the two arcs on either side of the slicing
line.

Before you start with this topic, create a new class that derives from
[GH_Component](T_Grasshopper_Kernel_GH_Component.htm), as outlined in the [My
First Component](b883d0c0-4947-48bc-8e9e-492a6d6c2a06.htm) topic.

![](../icons/SectionExpanded.png)Input parameters

This part of the component is very similar to the [Simple
Mathematics](2824c770-2673-49a3-8683-1a70bc0349cc.htm) topic. Except this time
there will be no default values.

VB

Copy

    
    
    ...
    Protected Overrides Sub RegisterInputParams(ByVal pManager As GH_Component.GH_InputParamManager)
      pManager.AddCircleParameter("Circle", "C", "The circle to slice", GH_ParamAccess.item)
      pManager.AddLineParameter("Line", "L", "Slicing line", GH_ParamAccess.item)
    End Sub
    ...

The first parameter is of type Param_Circle and the data it contains will
consist solely of [GH_Circle](T_Grasshopper_Kernel_Types_GH_Circle.htm).
GH_Circle is a class that wraps the Rhino.Geometry.Circle structure. It
provides methods that allow Grasshopper to incorporate RhinoCommon circles
into the default GUI. These methods include Archiving, Previewing, Baking and
Casting (Converting) functions. However, when accessing data inside a
Param_Circle parameter, you are not limited to the GH_Circle type, as we shall
see.

The second parameter is of type Param_Line and it works very similar to the
Param_Circle type discussed above.

![](../icons/SectionExpanded.png)Output parameters

Our component will output two arcs on success, or nulls on failure.

VB

Copy

    
    
    ...
    Protected Overrides Sub RegisterOutputParams(ByVal pManager As GH_Component.GH_OutputParamManager)
      pManager.AddArcParameter("Arc A", "A", "First Split result.", GH_ParamAccess.item)
      pManager.AddArcParameter("Arc B", "B", "Second Split result.", GH_ParamAccess.item)
    End Sub
    ...

![](../icons/SectionExpanded.png)SolveInstance

The SolveInstance() implementation for this component is responsible for the
following steps:

  1. Declare placeholder variables for the input data.
  2. Retrieve input data.
  3. Test input data for validity.
  4. Project line segment onto circle plane.
  5. Test projected segment for validity.
  6. Solve intersections for circle and projected segment.
  7. Abort on insufficient intersections.
  8. Create the slice arcs.
  9. Assign arcs to the output parameters.

Item 2 and 9 however can be approached from different directions. First I'll
show you the recommended approach and then we'll have a look at the
alternatives:

VB

Copy

    
    
    ...
    Protected Overrides Sub SolveInstance(ByVal DA As Grasshopper.Kernel.IGH_DataAccess)
      '1. Declare placeholder variables and assign initial invalid data.
      '   This way, if the input parameters fail to supply valid data, we know when to abort.
      Dim circle As Rhino.Geometry.Circle = Rhino.Geometry.Circle.Unset
      Dim line As Rhino.Geometry.Line = Rhino.Geometry.Line.Unset
    
      '2. Retrieve input data.
      If (Not DA.GetData(0, circle)) Then Return
      If (Not DA.GetData(1, line)) Then Return
    
      '3. Abort on invalid inputs.
      If (Not circle.IsValid) Then Return
      If (Not line.IsValid) Then Return
    
      '4. Project line segment onto circle plane.
      line.Transform(Rhino.Geometry.Transform.PlanarProjection(circle.Plane))
    
      '5. Test projected segment for validity.
      If (line.Length < Rhino.RhinoMath.ZeroTolerance) Then
        AddRuntimeMessage(GH_RuntimeMessageLevel.Error, "Line could not be projected onto the Circle plane")
        Return
      End If
    
      '6. Solve intersections and 7. Abort if there are less than two intersections.
      Dim t1 As Double
      Dim p1 As Rhino.Geometry.Point3d
      Dim t2 As Double
      Dim p2 As Rhino.Geometry.Point3d
    
      Select Case Rhino.Geometry.Intersect.Intersection.LineCircle(line, circle, t1, p1, t2, p2)
        Case Rhino.Geometry.Intersect.LineCircleIntersection.None
          AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, "No intersections were found")
          Return
        Case Rhino.Geometry.Intersect.LineCircleIntersection.Single
          AddRuntimeMessage(GH_RuntimeMessageLevel.Warning, "Only a single intersection was found")
          Return
      End Select
    
      '8. Create slicing arcs.
      Dim ct As Double
      circle.ClosestParameterTo(p1, ct)
    
      Dim tan As Rhino.Geometry.Vector3d = circle.TangentAt(ct)
    
      '9. Assign output arcs.
      DA.SetData(0, New Rhino.Geometry.Arc(p1, tan, p2))
      DA.SetData(1, New Rhino.Geometry.Arc(p1, -tan, p2))
    End Sub
    ...

As I mentioned before, the first input parameter is of type Param_Circle and
it contains data of type GH_Circle. But when we're accessing the parameter via
the DA.GetData(0, circle) method, we're using Rhino.Geometry.Circle instead of
Grasshopper.Kernel.Types.GH_Circle. The DA.GetData() method is capable of
converting data from the intrinsic parameter type into requested types,
provided the conversion makes sense. GH_Circle to Rhino.Geometry.Circle is a
perfectly valid conversion, GH_Circle to Rhino.Geometry.Transform would not
be.

The Grasshopper Component SDK has been designed on the premise that the bulk
of all Components that operate on data only care about the data itself, not
how it is wrapped up inside the Grasshopper data structures. The conversion
routines that translate GH_Circle data into Rhino.Geometry.Circle data (and
obviously also GH_Number into System.Double, and GH_Colour into
System.Drawing.Color etc.), have been highly optimised and should be used in
almost all circumstances.

If however you feel the need to get access to the GH_Circle data directly, you
can retrieve that instance in the same fashion:

VB

Copy

    
    
    ...
    Dim circle As Grasshopper.Kernel.Data.GH_Circle = Nothing
    If (Not DA.GetData(0, circle)) Then Return
    ...

Note that a single instance of GH_Circle may be shared among any number of
parameters in Grasshopper, and thus changing one will change data everywhere.
If you request Rhino.Geometry.Circle, System.Double or System.Drawing.Color
instead of GH_Circle, GH_Number or GH_Colour you won't have to worry about
this pitfall since you will always be given an object that has been
disassociated from the (potentially shared) wrapper type.

Similarly, you are allowed to store output data in different formats as well.
Instead of:

VB

Copy

    
    
    DA.SetData(0, New Rhino.Geometry.Arc(p1, tan, p2))

you could also provide an instance of Grasshopper.Kernel.Types.GH_Arc:

VB

Copy

    
    
    Dim gh_arc As New Grasshopper.Kernel.Types.GH_Arc(New Rhino.Geometry.Arc(p1, tan, p2))
    DA.SetData(0, gh_arc)

Grasshopper for Rhino 8.22.25217.12450 (2025-08-05)  
Copyright Â© 2009-2025 Robert McNeel & Associates

[Report wishes and bugs at
discourse.mcneel.com](https://discourse.mcneel.com/c/grasshopper)

