---
url: https://wiki.freecad.org/Arch_API
title: Arch API
scraped_at: 2025-09-08 16:42:22
---

# Arch API

  * [Page](/Arch_API "View the content page \[ctrl-option-c\]")
  * [Discussion](/index.php?title=Talk:Arch_API&action=edit&redlink=1 "Discussion about the content page \(page does not exist\) \[ctrl-option-t\]")

English

  * [Read](/Arch_API)
  * [Edit](/index.php?title=Arch_API&veaction=edit "Edit this page \[ctrl-option-v\]")
  * [Edit source](/index.php?title=Arch_API&action=edit "Edit the source code of this page \[ctrl-option-e\]")
  * [Edit on GitHub](https://github.com/Reqrefusion/FreeCAD-Documentation-Project/blob/main/wiki/Arch_API.wikitext "Edit this page on GitHub")
  * [View history](/index.php?title=Arch_API&action=history "Past revisions of this page \[ctrl-option-h\]")

Tools

Tools

move to sidebar hide

Actions

  * [Read](/Arch_API)
  * [Edit](/index.php?title=Arch_API&veaction=edit "Edit this page \[ctrl-option-v\]")
  * [Edit source](/index.php?title=Arch_API&action=edit "Edit the source code of this page \[ctrl-option-e\]")
  * [View history](/index.php?title=Arch_API&action=history)

General

  * [What links here](/Special:WhatLinksHere/Arch_API "A list of all wiki pages that link here \[ctrl-option-j\]")
  * [Related changes](/Special:RecentChangesLinked/Arch_API "Recent changes in pages linked from this page \[ctrl-option-k\]")
  * [Special pages](/Special:SpecialPages "A list of all special pages \[ctrl-option-q\]")
  * [Permanent link](https://wiki.freecad.org/index.php?title=Arch_API&oldid=1602931 "Permanent link to this revision of this page")
  * [Page information](/index.php?title=Arch_API&action=info "More information about this page")
  * Expand all

Print/export

  * [Download as PDF](/index.php?title=Special:DownloadAsPdf&page=Arch_API&action=show-download-screen)
  * [Printable version](javascript:print\(\); "Printable version of this page \[ctrl-option-p\]")

From FreeCAD Documentation

[Translate this page](/Special:Translate?group=page-
Arch+API&action=page&filter=&language=en)This is the approved revision of this
page, as well as being the most recent.

Other languages:

  * [](/index.php?title=Special:Translate&group=page-Arch+API&language=&task=view "Start translation for this language")
  * [Deutsch](/Arch_API/de "Arch API \(100% translated\)")
  * English
  * [Türkçe](/Arch_API/tr "Yapı API \(50% translated\)")
  * [français](/Arch_API/fr "API de l'atelier Arch \(100% translated\)")
  * [hrvatski](/Arch_API/hr "Graditelj API \(50% translated\)")
  * [italiano](/Arch_API/it "API Arch \(100% translated\)")
  * [polski](/Arch_API/pl "Architektura: API \(100% translated\)")
  * [română](/Arch_API/ro "Arch API \(50% translated\)")
  * [русский](/Arch_API/ru "Arch API/ru \(25% translated\)")

(November 2018) The Arch API is listed in the [autogenerated API
documentation](https://freecad.org/api).

The functions of the API are part of the [Arch Workbench](/Arch_Workbench
"Arch Workbench") and can be used in [macros](/Macros "Macros") and from the
[Python](/Python "Python") console once the `Arch` module has been imported.
The [Reinforcement Workbench](/Reinforcement_Workbench "Reinforcement
Workbench") has its own [Reinforcement API](/Reinforcement_API "Reinforcement
API").

Example:

    
    
    import FreeCAD, Draft, Arch
    
    p1 = FreeCAD.Vector(0, 0, 0)
    p2 = FreeCAD.Vector(2000, 0, 0)
    baseline = Draft.makeLine(p1, p2)
    
    Arch.makeWall(baseline, length=None, width=200, height=2000)
    

Expand[![](/images/0/05/Workbench_BIM.svg)](/index.php?title=File:Workbench_BIM.svg&filetimestamp=20240524155736&)
[BIM](/BIM_Workbench "BIM Workbench")

  * **2D drafting:** [Sketch](/BIM_Sketch "BIM Sketch"), [Line](/Draft_Line "Draft Line"), [Polyline](/Draft_Wire "Draft Wire"), [Circle](/Draft_Circle "Draft Circle"), [Arc](/Draft_Arc "Draft Arc"), [Arc by 3 points](/Draft_Arc_3Points "Draft Arc 3Points"), [Fillet](/Draft_Fillet "Draft Fillet"), [Ellipse](/Draft_Ellipse "Draft Ellipse"), [Polygon](/Draft_Polygon "Draft Polygon"), [Rectangle](/Draft_Rectangle "Draft Rectangle"), [B-spline](/Draft_BSpline "Draft BSpline"), [Bézier curve](/Draft_BezCurve "Draft BezCurve"), [Cubic Bézier curve](/Draft_CubicBezCurve "Draft CubicBezCurve"), [Point](/Draft_Point "Draft Point")

* * *

  * **3D/BIM:** [Project](/BIM_Project "BIM Project"), [Site](/Arch_Site "Arch Site"), [Building](/Arch_Building "Arch Building"), [Level](/Arch_Floor "Arch Floor"), [Space](/Arch_Space "Arch Space"), [Wall](/Arch_Wall "Arch Wall"), [Curtain Wall](/Arch_CurtainWall "Arch CurtainWall"), [Column](/BIM_Column "BIM Column"), [Beam](/BIM_Beam "BIM Beam"), [Slab](/BIM_Slab "BIM Slab"), [Door](/BIM_Door "BIM Door"), [Window](/Arch_Window "Arch Window"), [Pipe](/Arch_Pipe "Arch Pipe"), [Pipe Connector](/Arch_PipeConnector "Arch PipeConnector"), [Stairs](/Arch_Stairs "Arch Stairs"), [Roof](/Arch_Roof "Arch Roof"), [Panel](/Arch_Panel "Arch Panel"), [Frame](/Arch_Frame "Arch Frame"), [Fence](/Arch_Fence "Arch Fence"), [Truss](/Arch_Truss "Arch Truss"), [Equipment](/Arch_Equipment "Arch Equipment")
    * **Reinforcement tools:** [Custom Rebar](/Arch_Rebar "Arch Rebar"), [Straight Rebar](/Reinforcement_StraightRebar "Reinforcement StraightRebar"), [U-Shape Rebar](/Reinforcement_UShapeRebar "Reinforcement UShapeRebar"), [L-Shape Rebar](/Reinforcement_LShapeRebar "Reinforcement LShapeRebar"), [Stirrup](/Reinforcement_StirrupRebar "Reinforcement StirrupRebar"), [Bent-Shape Rebar](/Reinforcement_BentShapeRebar "Reinforcement BentShapeRebar"), [Helical Rebar](/Reinforcement_HelicalRebar "Reinforcement HelicalRebar"), [Column Reinforcement](/Reinforcement_ColumnRebars "Reinforcement ColumnRebars"), [Beam Reinforcement](/Reinforcement_BeamRebars "Reinforcement BeamRebars"), [Slab Reinforcement](/Reinforcement_SlabRebars "Reinforcement SlabRebars"), [Footing Reinforcement](/Reinforcement_FootingRebars "Reinforcement FootingRebars")
    * **Generic 3D tools:** [Profile](/Arch_Profile "Arch Profile"), [Box](/BIM_Box "BIM Box"), [Shape builder...](/Part_Builder "Part Builder"), [Facebinder](/Draft_Facebinder "Draft Facebinder"), [Objects library](/BIM_Library "BIM Library"), [Component](/Arch_Component "Arch Component"), [External reference](/Arch_Reference "Arch Reference")

* * *

  * **Annotation:** [Text](/BIM_Text "BIM Text"), [Shape from text](/Draft_ShapeString "Draft ShapeString"), [Aligned dimension](/BIM_DimensionAligned "BIM DimensionAligned"), [Horizontal dimension](/BIM_DimensionHorizontal "BIM DimensionHorizontal"), [Vertical dimension](/BIM_DimensionVertical "BIM DimensionVertical"), [Leader](/BIM_Leader "BIM Leader"), [Label](/Draft_Label "Draft Label"), [Axis](/Arch_Axis "Arch Axis"), [Axes System](/Arch_AxisSystem "Arch AxisSystem"), [Grid](/Arch_Grid "Arch Grid"), [Section Plane](/Arch_SectionPlane "Arch SectionPlane"), [Hatch](/Draft_Hatch "Draft Hatch"), [Page](/BIM_TDPage "BIM TDPage"), [View](/BIM_TDView "BIM TDView"), [Shape-based view](/BIM_Shape2DView "BIM Shape2DView")

* * *

  * **[Snapping](/Draft_Snap "Draft Snap"):** [Snap lock](/Draft_Snap_Lock "Draft Snap Lock"), [Snap endpoint](/Draft_Snap_Endpoint "Draft Snap Endpoint"), [Snap midpoint](/Draft_Snap_Midpoint "Draft Snap Midpoint"), [Snap center](/Draft_Snap_Center "Draft Snap Center"), [Snap angle](/Draft_Snap_Angle "Draft Snap Angle"), [Snap intersection](/Draft_Snap_Intersection "Draft Snap Intersection"), [Snap perpendicular](/Draft_Snap_Perpendicular "Draft Snap Perpendicular"), [Snap extension](/Draft_Snap_Extension "Draft Snap Extension"), [Snap parallel](/Draft_Snap_Parallel "Draft Snap Parallel"), [Snap special](/Draft_Snap_Special "Draft Snap Special"), [Snap near](/Draft_Snap_Near "Draft Snap Near"), [Snap ortho](/Draft_Snap_Ortho "Draft Snap Ortho"), [Snap grid](/Draft_Snap_Grid "Draft Snap Grid"), [Snap working plane](/Draft_Snap_WorkingPlane "Draft Snap WorkingPlane"), [Snap dimensions](/Draft_Snap_Dimensions "Draft Snap Dimensions"), [Toggle grid](/Draft_ToggleGrid "Draft ToggleGrid"), [Working Plane Top](/BIM_SetWPTop "BIM SetWPTop"), [Working Plane Front](/BIM_SetWPFront "BIM SetWPFront"), [Working Plane Side](/BIM_SetWPSide "BIM SetWPSide")

* * *

  * **Modify:** [Move](/Draft_Move "Draft Move"), [Copy](/BIM_Copy "BIM Copy"), [Rotate](/Draft_Rotate "Draft Rotate"), [Clone](/BIM_Clone "BIM Clone"), [Create simple copy](/BIM_SimpleCopy "BIM SimpleCopy"), [Make compound](/BIM_Compound "BIM Compound"), [Offset](/Draft_Offset "Draft Offset"), [2D Offset...](/BIM_Offset2D "BIM Offset2D"), [Trimex](/Draft_Trimex "Draft Trimex"), [Join](/Draft_Join "Draft Join"), [Split](/Draft_Split "Draft Split"), [Scale](/Draft_Scale "Draft Scale"), [Stretch](/Draft_Stretch "Draft Stretch"), [Draft to sketch](/Draft_Draft2Sketch "Draft Draft2Sketch"), [Upgrade](/Draft_Upgrade "Draft Upgrade"), [Downgrade](/Draft_Downgrade "Draft Downgrade"), [Add component](/Arch_Add "Arch Add"), [Remove component](/Arch_Remove "Arch Remove"), [Array](/Draft_OrthoArray "Draft OrthoArray"), [Path array](/Draft_PathArray "Draft PathArray"), [Polar array](/Draft_PolarArray "Draft PolarArray"), [Point array](/Draft_PointArray "Draft PointArray"), [Cut with plane](/Arch_CutPlane "Arch CutPlane"), [Mirror](/Draft_Mirror "Draft Mirror"), [Extrude...](/BIM_Extrude "BIM Extrude"), [Difference](/BIM_Cut "BIM Cut"), [Union](/BIM_Fuse "BIM Fuse"), [Intersection](/BIM_Common "BIM Common")

* * *

  * **Manage:** [BIM Setup...](/BIM_Setup "BIM Setup"), [Views manager](/BIM_Views "BIM Views"), [Manage project...](/BIM_ProjectManager "BIM ProjectManager"), [Manage doors and windows...](/BIM_Windows "BIM Windows"), [Manage IFC elements...](/BIM_IfcElements "BIM IfcElements"), [Manage IFC quantities...](/BIM_IfcQuantities "BIM IfcQuantities"), [Manage IFC properties...](/BIM_IfcProperties "BIM IfcProperties"), [Manage classification...](/BIM_Classification "BIM Classification"), [Manage layers...](/BIM_Layers "BIM Layers"), [Material](/BIM_Material "BIM Material"), [Schedule](/Arch_Schedule "Arch Schedule"), [Preflight checks...](/BIM_Preflight "BIM Preflight"), [Annotation styles...](/Draft_AnnotationStyleEditor "Draft AnnotationStyleEditor")

* * *

  * **Utils:** [Toggle bottom panels](/BIM_TogglePanels "BIM TogglePanels"), [Move to Trash](/BIM_Trash "BIM Trash"), [Working Plane View](/BIM_WPView "BIM WPView"), [Select group](/Draft_SelectGroup "Draft SelectGroup"), [Set slope](/Draft_Slope "Draft Slope"), [Create working plane proxy](/Draft_WorkingPlaneProxy "Draft WorkingPlaneProxy"), [Add to construction group](/Draft_AddConstruction "Draft AddConstruction"), [Split Mesh](/Arch_SplitMesh "Arch SplitMesh"), [Mesh to Shape](/Arch_MeshToShape "Arch MeshToShape"), [Select non-manifold meshes](/Arch_SelectNonSolidMeshes "Arch SelectNonSolidMeshes"), [Remove Shape from Arch](/Arch_RemoveShape "Arch RemoveShape"), [Close Holes](/Arch_CloseHoles "Arch CloseHoles"), [Merge Walls](/Arch_MergeWalls "Arch MergeWalls"), [Check](/Arch_Check "Arch Check"), [Toggle IFC Brep flag](/Arch_ToggleIfcBrepFlag "Arch ToggleIfcBrepFlag"), [Toggle subcomponents](/Arch_ToggleSubs "Arch ToggleSubs"), [Survey](/Arch_Survey "Arch Survey"), [IFC Diff](/BIM_Diff "BIM Diff"), [IFC explorer](/BIM_IfcExplorer "BIM IfcExplorer"), [Create IFC spreadsheet...](/Arch_IfcSpreadsheet "Arch IfcSpreadsheet"), [Image plane](/index.php?title=BIM_ImagePlane&action=edit&redlink=1 "BIM ImagePlane \(page does not exist\)"), [Unclone](/index.php?title=BIM_Unclone&action=edit&redlink=1 "BIM Unclone \(page does not exist\)"), [Rewire](/index.php?title=BIM_Rewire&action=edit&redlink=1 "BIM Rewire \(page does not exist\)"), [Glue](/index.php?title=BIM_Glue&action=edit&redlink=1 "BIM Glue \(page does not exist\)"), [Reextrude](/index.php?title=BIM_Reextrude&action=edit&redlink=1 "BIM Reextrude \(page does not exist\)")
    * **Panel tools:** [Panel](/Arch_Panel "Arch Panel"), [Panel Cut](/Arch_Panel_Cut "Arch Panel Cut"), [Panel Sheet](/Arch_Panel_Sheet "Arch Panel Sheet"), [Nest](/Arch_Nest "Arch Nest")
    * **Structure tools:** [Structure](/Arch_Structure "Arch Structure"), [Structural System](/index.php?title=Arch_StructuralSystem&action=edit&redlink=1 "Arch StructuralSystem \(page does not exist\)"), [Multiple Structures](/index.php?title=Arch_StructuresFromSelection&action=edit&redlink=1 "Arch StructuresFromSelection \(page does not exist\)")
    * **IFC tools:** [IFC Diff...](/index.php?title=IFC_Diff&action=edit&redlink=1 "IFC Diff \(page does not exist\)"), [IFC Expand](/index.php?title=IFC_Expand&action=edit&redlink=1 "IFC Expand \(page does not exist\)"), [Make IFC project](/index.php?title=IFC_MakeProject&action=edit&redlink=1 "IFC MakeProject \(page does not exist\)"), [IfcOpenShell update](/index.php?title=IFC_UpdateIOS&action=edit&redlink=1 "IFC UpdateIOS \(page does not exist\)")
    * **Nudge:** [Nudge Switch](/index.php?title=BIM_Nudge_Switch&action=edit&redlink=1 "BIM Nudge Switch \(page does not exist\)"), [Nudge Up](/index.php?title=BIM_Nudge_Up&action=edit&redlink=1 "BIM Nudge Up \(page does not exist\)"), [Nudge Down](/index.php?title=BIM_Nudge_Down&action=edit&redlink=1 "BIM Nudge Down \(page does not exist\)"), [Nudge Left](/index.php?title=BIM_Nudge_Left&action=edit&redlink=1 "BIM Nudge Left \(page does not exist\)"), [Nudge Right](/index.php?title=BIM_Nudge_Right&action=edit&redlink=1 "BIM Nudge Right \(page does not exist\)"), [Nudge Rotate Left](/index.php?title=BIM_Nudge_RotateLeft&action=edit&redlink=1 "BIM Nudge RotateLeft \(page does not exist\)"), [Nudge Rotate Right](/index.php?title=BIM_Nudge_RotateRight&action=edit&redlink=1 "BIM Nudge RotateRight \(page does not exist\)"), [Nudge Extend](/index.php?title=BIM_Nudge_Extend&action=edit&redlink=1 "BIM Nudge Extend \(page does not exist\)"), [Nudge Shrink](/index.php?title=BIM_Nudge_Shrink&action=edit&redlink=1 "BIM Nudge Shrink \(page does not exist\)")

* * *

  * **Additional:** [Preferences](/BIM_Preferences "BIM Preferences"), [Fine tuning](/Fine-tuning "Fine-tuning"), [Import Export Preferences](/Import_Export_Preferences "Import Export Preferences"), [IFC](/Arch_IFC "Arch IFC"), [DAE](/Arch_DAE "Arch DAE"), [OBJ](/Arch_OBJ "Arch OBJ"), [JSON](/Arch_JSON "Arch JSON"), [3DS](/Arch_3DS "Arch 3DS"), [SHP](/Arch_SHP "Arch SHP")

Expand[![](/images/thumb/9/94/User_hub.png/24px-
User_hub.png)](/index.php?title=File:User_hub.png&filetimestamp=20190221145008&)
[User documentation](/User_hub "User hub")

  * **[Getting started](/Getting_started "Getting started")**
  * **Installation:** [Download](/Download "Download"), [Windows](/Installing_on_Windows "Installing on Windows"), [Linux](/Installing_on_Linux "Installing on Linux"), [Mac](/Installing_on_Mac "Installing on Mac"), [Additional components](/Installing_additional_components "Installing additional components"), [Docker](/Compile_on_Docker "Compile on Docker"), [AppImage](/AppImage "AppImage"), [Ubuntu Snap](/Ubuntu_Snap "Ubuntu Snap")
  * **Basics:** [About FreeCAD](/About_FreeCAD "About FreeCAD"), [Interface](/Interface "Interface"), [Mouse navigation](/Mouse_navigation "Mouse navigation"), [Selection methods](/Selection_methods "Selection methods"), [Object name](/Object_name "Object name"), [Preferences](/Preferences_Editor "Preferences Editor"), [Workbenches](/Workbenches "Workbenches"), [Document structure](/Document_structure "Document structure"), [Properties](/Property "Property"), [Help FreeCAD](/Help_FreeCAD "Help FreeCAD"), [Donate](/Donate "Donate")

* * *

  * **Help:** [Tutorials](/Tutorials "Tutorials"), [Video tutorials](/Video_tutorials "Video tutorials")
  * **[Workbenches](/Workbenches "Workbenches"):** [Std Base](/Std_Base "Std Base"), [Assembly](/Assembly_Workbench "Assembly Workbench"), [BIM](/BIM_Workbench "BIM Workbench"), [CAM](/CAM_Workbench "CAM Workbench"), [Draft](/Draft_Workbench "Draft Workbench"), [FEM](/FEM_Workbench "FEM Workbench"), [Inspection](/Inspection_Workbench "Inspection Workbench"), [Material](/Material_Workbench "Material Workbench"), [Mesh](/Mesh_Workbench "Mesh Workbench"), [OpenSCAD](/OpenSCAD_Workbench "OpenSCAD Workbench"), [Part](/Part_Workbench "Part Workbench"), [PartDesign](/PartDesign_Workbench "PartDesign Workbench"), [Points](/Points_Workbench "Points Workbench"), [Reverse Engineering](/Reverse_Engineering_Workbench "Reverse Engineering Workbench"), [Robot](/Robot_Workbench "Robot Workbench"), [Sketcher](/Sketcher_Workbench "Sketcher Workbench"), [Spreadsheet](/Spreadsheet_Workbench "Spreadsheet Workbench"), [Surface](/Surface_Workbench "Surface Workbench"), [TechDraw](/TechDraw_Workbench "TechDraw Workbench"), [Test Framework](/Testing "Testing")

* * *

  * **[Addons](/Addon "Addon"):** [Addon Manager](/Std_AddonMgr "Std AddonMgr"), [External workbenches](/External_workbenches "External workbenches"), [Scripting and macros](/Scripting_and_macros "Scripting and macros")

* * *

  * **Hubs:** [User hub](/User_hub "User hub"), [Power users hub](/Power_users_hub "Power users hub"), [Developer hub](/Developer_hub "Developer hub")

