---
url: https://wiki.freecad.org/Sketcher_Workbench
title: Sketcher Workbench
scraped_at: 2025-09-08 16:44:28
---

Toggle the table of contents

## Contents

move to sidebar hide

  * Beginning
  * 1 Introduction
  * 2 Constraints Toggle Constraints subsection
    * 2.1 Edit constraints
    * 2.2 Reposition constraints
  * 3 Profile sketches
  * 4 Tools Toggle Tools subsection
    * 4.1 General
      * 4.1.1 Sketcher toolbar
      * 4.1.2 Sketcher Edit Mode toolbar
      * 4.1.3 Sketcher edit tools toolbar
      * 4.1.4 Other
    * 4.2 Sketcher geometries
    * 4.3 Sketcher constraints
    * 4.4 Sketcher tools
    * 4.5 Sketcher B-spline tools
    * 4.6 Sketcher visual
    * 4.7 Obsolete tools
  * 5 Preferences
  * 6 Drawing aids Toggle Drawing aids subsection
    * 6.1 Continue modes
    * 6.2 Auto constraints
    * 6.3 Snapping
    * 6.4 On-View-Parameters
    * 6.5 Coordinate display
  * 7 Selection methods Toggle Selection methods subsection
    * 7.1 3D view element selection
    * 7.2 3D view box selection
    * 7.3 3D view connected geometry selection
    * 7.4 Sketcher Dialog selection
  * 8 Copy, cut and paste
  * 9 Best practices
  * 10 Flipping Toggle Flipping subsection
    * 10.1 Methods to reduce flipping
      * 10.1.1 Change dimensions in small increments
      * 10.1.2 Use a different solver
      * 10.1.3 Use horizontal and vertical dimensions
      * 10.1.4 Use angular dimensions
  * 11 Tutorials
  * 12 Scripting
  * 13 Examples

# Sketcher Workbench

  * [Page](/Sketcher_Workbench "View the content page \[ctrl-option-c\]")
  * [Discussion](/Talk:Sketcher_Workbench "Discussion about the content page \[ctrl-option-t\]")

English

  * [Read](/Sketcher_Workbench)
  * [Edit](/index.php?title=Sketcher_Workbench&veaction=edit "Edit this page \[ctrl-option-v\]")
  * [Edit source](/index.php?title=Sketcher_Workbench&action=edit "Edit the source code of this page \[ctrl-option-e\]")
  * [Edit on GitHub](https://github.com/Reqrefusion/FreeCAD-Documentation-Project/blob/main/wiki/Sketcher_Workbench.wikitext "Edit this page on GitHub")
  * [View history](/index.php?title=Sketcher_Workbench&action=history "Past revisions of this page \[ctrl-option-h\]")

Tools

Tools

move to sidebar hide

Actions

  * [Read](/Sketcher_Workbench)
  * [Edit](/index.php?title=Sketcher_Workbench&veaction=edit "Edit this page \[ctrl-option-v\]")
  * [Edit source](/index.php?title=Sketcher_Workbench&action=edit "Edit the source code of this page \[ctrl-option-e\]")
  * [View history](/index.php?title=Sketcher_Workbench&action=history)

General

  * [What links here](/Special:WhatLinksHere/Sketcher_Workbench "A list of all wiki pages that link here \[ctrl-option-j\]")
  * [Related changes](/Special:RecentChangesLinked/Sketcher_Workbench "Recent changes in pages linked from this page \[ctrl-option-k\]")
  * [Special pages](/Special:SpecialPages "A list of all special pages \[ctrl-option-q\]")
  * [Permanent link](https://wiki.freecad.org/index.php?title=Sketcher_Workbench&oldid=1624245 "Permanent link to this revision of this page")
  * [Page information](/index.php?title=Sketcher_Workbench&action=info "More information about this page")
  * Expand all

Print/export

  * [Download as PDF](/index.php?title=Special:DownloadAsPdf&page=Sketcher_Workbench&action=show-download-screen)
  * [Printable version](javascript:print\(\); "Printable version of this page \[ctrl-option-p\]")

From FreeCAD Documentation

[Translate this page](/Special:Translate?group=page-
Sketcher+Workbench&action=page&filter=&language=en)This is the approved
revision of this page, as well as being the most recent.

Other languages:

  * [](/index.php?title=Special:Translate&group=page-Sketcher+Workbench&language=&task=view "Start translation for this language")
  * [Bahasa Indonesia](/Sketcher_Workbench/id "Sketcher Workbench \(0% translated\)")
  * [Deutsch](/Sketcher_Workbench/de "Arbeitsbereich Sketcher \(100% translated\)")
  * English
  * [Türkçe](/Sketcher_Workbench/tr "Eskiz Tezgahı \(4% translated\)")
  * [español](/Sketcher_Workbench/es "Ambiente de trabajo Croquizador \(7% translated\)")
  * [français](/Sketcher_Workbench/fr "Atelier Sketcher \(100% translated\)")
  * [hrvatski](/Sketcher_Workbench/hr "Sketcher Workbench/hr \(1% translated\)")
  * [italiano](/Sketcher_Workbench/it "Ambiente Sketcher \(100% translated\)")
  * [magyar](/Sketcher_Workbench/hu "Sketcher Workbench \(0% translated\)")
  * [polski](/Sketcher_Workbench/pl "Środowisko pracy Szkicownik \(100% translated\)")
  * [português](/Sketcher_Workbench/pt "Sketcher Workbench \(0% translated\)")
  * [português do Brasil](/Sketcher_Workbench/pt-br "Bancada de trabalho Sketcher \(14% translated\)")
  * [română](/Sketcher_Workbench/ro "Sketcher Workbench \(4% translated\)")
  * [slovenčina](/Sketcher_Workbench/sk "Pracovný stôl Náčrtník \(8% translated\)")
  * [suomi](/Sketcher_Workbench/fi "Sketcher Workbench \(0% translated\)")
  * [svenska](/Sketcher_Workbench/sv "Sketcher Workbench \(0% translated\)")
  * [čeština](/Sketcher_Workbench/cs "Pracovní plocha Skicář \(1% translated\)")
  * [български](/Sketcher_Workbench/bg "Sketcher Workbench/bg \(0% translated\)")
  * [русский](/Sketcher_Workbench/ru "Верстак Sketcher \(Скетчер\) \(93% translated\)")
  * [українська](/Sketcher_Workbench/uk "Sketcher Workbench \(0% translated\)")
  * [中文](/Sketcher_Workbench/zh "Sketcher Workbench/zh \(0% translated\)")
  * [中文（中国大陆）](/Sketcher_Workbench/zh-cn "草图工作台 \(3% translated\)")
  * [中文（繁體）](/Sketcher_Workbench/zh-hant "Sketcher Workbench \(0% translated\)")
  * [中文（臺灣）](/Sketcher_Workbench/zh-tw "速寫坊 \(0% translated\)")
  * [日本語](/Sketcher_Workbench/ja "スケッチャーワークベンチ \(93% translated\)")
  * [한국어](/Sketcher_Workbench/ko "스케치 작업대 \(83% translated\)")

![](/images/6/6f/Arrow-left.svg) ![](/images/e/e3/Workbench_Robot.svg) [Robot
Workbench](/Robot_Workbench "Robot Workbench")

![](/images/b/be/Workbench_Spreadsheet.svg) [Spreadsheet
Workbench](/Spreadsheet_Workbench "Spreadsheet Workbench")
![](/images/a/af/Arrow-right.svg)

[Index](/Online_Help_Toc "Online Help Toc")
![](/images/7/76/Online_Help_Toc.svg)

[![](/images/9/91/Workbench_Sketcher.svg)](/index.php?title=File:Workbench_Sketcher.svg&filetimestamp=20231231194727&)Sketcher
workbench icon

## Introduction

With the
[![](/images/9/91/Workbench_Sketcher.svg)](/index.php?title=File:Workbench_Sketcher.svg&filetimestamp=20231231194727&)
Sketcher Workbench 2D sketches intended for use in other workbenches can be
created. 2D sketches are the starting point for many CAD models. They
typically define the profiles and paths for operations to create 3D shapes. A
model may depend on several sketches for its final shape.

Together with boolean operations defined in the
[![](/images/0/04/Workbench_Part.svg)](/index.php?title=File:Workbench_Part.svg&filetimestamp=20240712190040&)
[Part Workbench](/Part_Workbench "Part Workbench"), the Sketcher Workbench, or
"The Sketcher" for short, forms the basis of the [constructive solid
geometry](/Constructive_solid_geometry "Constructive solid geometry") (CSG)
method of building solids. Together with
[![](/images/3/39/Workbench_PartDesign.svg)](/index.php?title=File:Workbench_PartDesign.svg&filetimestamp=20240405092932&)
[PartDesign Workbench](/PartDesign_Workbench "PartDesign Workbench")
operations, it also forms the basis of the [feature editing](/Feature_editing
"Feature editing") methodology of creating solids. But many other workbenches
use sketches as well.

The Sketcher workbench features constraints, allowing 2D shapes to follow
precise geometrical definitions in terms of length, angles, and relationships
(horizontality, verticality, perpendicularity, etc.). A constraint solver
calculates the constrained-extent of 2D geometry and allows interactive
exploration of the degrees-of-freedom of the sketch.

The Sketcher is not intended for producing 2D blueprints. Once sketches are
used to generate a solid feature, they are automatically hidden and
Constraints are only visible in Sketch edit mode. If you only need to produce
2D views for print, and don't want to create 3D models, check out the [Draft
workbench](/Draft_Workbench "Draft Workbench").

[![](/images/thumb/7/71/FC_ConstrainedSketch.png/450px-
FC_ConstrainedSketch.png)](/index.php?title=File:FC_ConstrainedSketch.png&filetimestamp=20180803221416&)

A fully constrained sketch

## Constraints

Constraints are used to limit the degrees of freedom of an object. For
example, a line without constraints has 4 degrees of freedom (abbreviated as
"DoF"): it can be moved horizontally or vertically, it can be stretched, and
it can be rotated.

Applying a horizontal or vertical constraint, or an angle constraint (relative
to another line or to one of the axes), will limit its capacity to rotate,
thus leaving it with 3 degrees of freedom. Locking one of its points in
relation to the origin will remove another 2 degrees of freedom. And applying
a dimension constraint will remove the last degree of freedom. The line is
then considered **fully-constrained**.

Objects can be constrained in relation to one another. Two lines can be joined
through one of their points with the coincident point constraint. An angle can
be set between them, or they can be set perpendicular. A line can be tangent
to an arc or a circle, and so on. A Sketch may have a number of different
solutions, and making it **fully-constrained** can mean that just one of these
possible solutions has been reached based on the applied constraints. See
also: Flipping.

There are two kinds of constraints: geometric and dimensional. They are
detailed in the Tools section below.

### Edit constraints

When a [driving dimensional constraint](/Sketcher_ToggleDrivingConstraint
"Sketcher ToggleDrivingConstraint") is created, and if the **Ask for value
after creating a dimensional constraint**
[preference](/Sketcher_Preferences#Display "Sketcher Preferences") is selected
(default), a dialog opens to edit its value.

[![Sketcher_Edit_Constraint.png](/images/7/79/Sketcher_Edit_Constraint.png)](/index.php?title=File:Sketcher_Edit_Constraint.png&filetimestamp=20240311180650&
"Sketcher_Edit_Constraint.png")

You can enter a numerical value or an [expression](/Expressions
"Expressions"), and it is possible to name the constraint to facilitate its
use in other expressions. You can also check the **Reference** checkbox to
switch the constrain to [reference mode](/Sketcher_ToggleDrivingConstraint
"Sketcher ToggleDrivingConstraint").

To edit the value of an existing dimensional constraint do one of the
following:

  * Double-click the constraint value in the [3D view](/3D_view "3D view").
  * Double-click the constraint in the [Sketcher Dialog](/Sketcher_Dialog "Sketcher Dialog").
  * Right-click the constraint in the Sketcher Dialog and select the **Change value** option from the context menu.

### Reposition constraints

Dimensional constraints can be repositioned in the 3D view by dragging. Hold
down the left mouse button over the constraint value and move the mouse. The
symbols of geometric constraints are positioned automatically and cannot be
moved.

## Profile sketches

To create a sketch that can be used as a profile for generating solids certain
rules must be followed:

  * The sketch must contain only closed contours. Gaps between endpoints, however small, are not allowed.
  * Contours can be nested, to create voids, but should not self-intersect or intersect other contours.
  * Contours cannot share edges with other contours. Duplicate edges must be avoided.
  * T-connections, that is more than two edges sharing a common point, or a point touching an edge, are not allowed.

These rules do not apply to construction geometry (default color blue), which
is not shown outside edit mode, or if the sketch is used for a different
purpose. Depending on the workbench and the tool that will use the profile
sketch, additional restrictions may apply.

## Tools

The Sketcher Workbench tools are located in the Sketch menu and/or several
toolbars. [introduced in 0.21](/Release_notes_0.21 "Release notes 0.21"):
Almost all Sketcher toolbars are only displayed while a sketch is in edit
mode. The only exception is the Sketcher toolbar which is only displayed if no
sketch is in edit mode.

Some tools are also available from the [3D view](/3D_view "3D view") context
menu while a sketch is in edit mode, or from the context menus of the
[Sketcher Dialog](/Sketcher_Dialog "Sketcher Dialog").

[introduced in 0.21](/Release_notes_0.21 "Release notes 0.21"): If a sketch is
in edit mode the Structure toolbar is hidden as none of its tools can then be
used.

### General

#### Sketcher toolbar

  * [![](/images/f/f1/Sketcher_NewSketch.svg)](/index.php?title=File:Sketcher_NewSketch.svg&filetimestamp=20231231201726&) [Create sketch](/Sketcher_NewSketch "Sketcher NewSketch"): Creates a new sketch and opens the [Sketcher Dialog](/Sketcher_Dialog "Sketcher Dialog") to edit it.

  * [![](/images/c/c2/Sketcher_EditSketch.svg)](/index.php?title=File:Sketcher_EditSketch.svg&filetimestamp=20231231201543&) [Edit sketch](/Sketcher_EditSketch "Sketcher EditSketch"): Opens the Sketcher Dialog to edit an existing sketch.

  * [![](/images/d/df/Sketcher_MapSketch.svg)](/index.php?title=File:Sketcher_MapSketch.svg&filetimestamp=20231231201639&) [Attach sketch](/Sketcher_MapSketch "Sketcher MapSketch"): Attaches a sketch to selected geometry.

  * [![](/images/e/e3/Sketcher_ReorientSketch.svg)](/index.php?title=File:Sketcher_ReorientSketch.svg&filetimestamp=20231231201806&) [Reorient sketch](/Sketcher_ReorientSketch "Sketcher ReorientSketch"): Places a sketch on one of the main planes with an optional offset. It can also be used to detach a sketch.

  * [![](/images/d/d3/Sketcher_ValidateSketch.svg)](/index.php?title=File:Sketcher_ValidateSketch.svg&filetimestamp=20231231201854&) [Validate sketch](/Sketcher_ValidateSketch "Sketcher ValidateSketch"): Can analyze and repair a sketch that is no longer editable or has invalid constraints, or add missing coincident constraints.

  * [![](/images/2/24/Sketcher_MergeSketches.svg)](/index.php?title=File:Sketcher_MergeSketches.svg&filetimestamp=20240101165337&) [Merge sketches](/Sketcher_MergeSketches "Sketcher MergeSketches"): Merges two or more sketches.

  * [![](/images/c/cd/Sketcher_MirrorSketch.svg)](/index.php?title=File:Sketcher_MirrorSketch.svg&filetimestamp=20231231201710&) [Mirror sketch](/Sketcher_MirrorSketch "Sketcher MirrorSketch"): Mirrors sketches across their X axis, Y axis, or origin.

#### Sketcher Edit Mode toolbar

  * [![](/images/3/3a/Sketcher_LeaveSketch.svg)](/index.php?title=File:Sketcher_LeaveSketch.svg&filetimestamp=20231231201626&) [Leave sketch](/Sketcher_LeaveSketch "Sketcher LeaveSketch"): Finishes sketch edit mode and closes the [Sketcher Dialog](/Sketcher_Dialog "Sketcher Dialog").

  * [![](/images/f/f7/Sketcher_ViewSketch.svg)](/index.php?title=File:Sketcher_ViewSketch.svg&filetimestamp=20231231201925&) [View sketch](/Sketcher_ViewSketch "Sketcher ViewSketch"): Aligns the [3D view](/3D_view "3D view") with the sketch.

  * [![](/images/e/e8/Sketcher_ViewSection.svg)](/index.php?title=File:Sketcher_ViewSection.svg&filetimestamp=20231231201908&) [View section](/Sketcher_ViewSection "Sketcher ViewSection"): Toggles a temporary section plane that hides any objects and parts of objects in front of the sketch plane.

#### Sketcher edit tools toolbar

  * [![](/images/3/3e/Sketcher_Grid.svg)](/index.php?title=File:Sketcher_Grid.svg&filetimestamp=20240101165646&) [Toggle grid](/Sketcher_Grid "Sketcher Grid"): Toggles the grid in the sketch currently being edited. Settings can be changed in the related menu. [introduced in 0.21](/Release_notes_0.21 "Release notes 0.21")

  * [![](/images/c/c0/Sketcher_Snap.svg)](/index.php?title=File:Sketcher_Snap.svg&filetimestamp=20231231201816&) [Toggle snap](/Sketcher_Snap "Sketcher Snap"): Toggles snapping in all sketches. Settings can be changed in the related menu. [introduced in 0.21](/Release_notes_0.21 "Release notes 0.21")

  * [![](/images/6/63/Sketcher_RenderingOrder.svg)](/index.php?title=File:Sketcher_RenderingOrder.svg&filetimestamp=20240101165700&) [Configure rendering order](/Sketcher_RenderingOrder "Sketcher RenderingOrder"): The rendering order of all sketches can be changed in the related menu. [introduced in 0.21](/Release_notes_0.21 "Release notes 0.21")

#### Other

  * [![](/images/9/96/Sketcher_StopOperation.svg)](/index.php?title=File:Sketcher_StopOperation.svg&filetimestamp=20201015163520&) [Stop operation](/Sketcher_StopOperation "Sketcher StopOperation"): Stops any currently running geometry or constraint creation tool.

### Sketcher geometries

These are tools for creating objects.

  * [![](/images/6/6f/Sketcher_CreatePoint.svg)](/index.php?title=File:Sketcher_CreatePoint.svg&filetimestamp=20240101090735&) [Point](/Sketcher_CreatePoint "Sketcher CreatePoint"): Creates a point.

  * [![](/images/b/bd/Sketcher_CreatePolyline.svg)](/index.php?title=File:Sketcher_CreatePolyline.svg&filetimestamp=20240101090758&) [Polyline](/Sketcher_CreatePolyline "Sketcher CreatePolyline"): Creates a series of line and arc segments connected by their endpoints. The tool has several modes.

  * [![](/images/b/bd/Sketcher_CreateLine.svg)](/index.php?title=File:Sketcher_CreateLine.svg&filetimestamp=20240101090429&) [Line](/Sketcher_CreateLine "Sketcher CreateLine"): Creates a line. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): The tool has three modes.

  * [![](/images/b/be/Sketcher_CreateArc.svg)](/index.php?title=File:Sketcher_CreateArc.svg&filetimestamp=20240101085740&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) Create arc:

    

  * [![](/images/b/be/Sketcher_CreateArc.svg)](/index.php?title=File:Sketcher_CreateArc.svg&filetimestamp=20240101085740&) [Arc by center](/Sketcher_CreateArc "Sketcher CreateArc"): Creates an arc by its center and its endpoints. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): Or by its endpoints and a point along the arc.

    

  * [![](/images/c/c9/Sketcher_Create3PointArc.svg)](/index.php?title=File:Sketcher_Create3PointArc.svg&filetimestamp=20240101085650&) [Arc by 3 points](/Sketcher_Create3PointArc "Sketcher Create3PointArc"): Creates an arc by its endpoints and a point along the arc. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): This is the same tool as [Arc by center](/Sketcher_CreateArc "Sketcher CreateArc") but with a different initial mode.

    

  * [![](/images/1/1b/Sketcher_CreateArcOfEllipse.svg)](/index.php?title=File:Sketcher_CreateArcOfEllipse.svg&filetimestamp=20240101170312&) [Arc of ellipse](/Sketcher_CreateArcOfEllipse "Sketcher CreateArcOfEllipse"): Creates an arc of ellipse.

    

  * [![](/images/e/ee/Sketcher_CreateArcOfHyperbola.svg)](/index.php?title=File:Sketcher_CreateArcOfHyperbola.svg&filetimestamp=20240101170323&) [Arc of hyperbola](/Sketcher_CreateArcOfHyperbola "Sketcher CreateArcOfHyperbola"): Creates an arc of hyperbola.

    

  * [![](/images/a/ae/Sketcher_CreateArcOfParabola.svg)](/index.php?title=File:Sketcher_CreateArcOfParabola.svg&filetimestamp=20240101170333&) [Arc of parabola](/Sketcher_CreateArcOfParabola "Sketcher CreateArcOfParabola"): Creates an arc of parabola.

  * [![](/images/3/3f/Sketcher_CreateCircle.svg)](/index.php?title=File:Sketcher_CreateCircle.svg&filetimestamp=20240101085932&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) Create circle/ellipse:

    

  * [![](/images/3/3f/Sketcher_CreateCircle.svg)](/index.php?title=File:Sketcher_CreateCircle.svg&filetimestamp=20240101085932&) [Circle by center](/Sketcher_CreateCircle "Sketcher CreateCircle"): Creates a circle by its center and a point along the circle. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): Or by three points along the circle.

    

  * [![](/images/2/27/Sketcher_Create3PointCircle.svg)](/index.php?title=File:Sketcher_Create3PointCircle.svg&filetimestamp=20240101085716&) [Circle by 3 points](/Sketcher_Create3PointCircle "Sketcher Create3PointCircle"): Creates a circle by three points along the circle. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): This is the same tool as [Circle by center](/Sketcher_CreateCircle "Sketcher CreateCircle") but with a different initial mode.

    

  * [![](/images/6/61/Sketcher_CreateEllipseByCenter.svg)](/index.php?title=File:Sketcher_CreateEllipseByCenter.svg&filetimestamp=20240101090023&) [Ellipse by center](/Sketcher_CreateEllipseByCenter "Sketcher CreateEllipseByCenter"): Creates an ellipse by its center, an endpoint of one of its axes, and a point along the ellipse. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): Or by both endpoints of one of its axes and a point along the ellipse.

    

  * [![](/images/2/29/Sketcher_CreateEllipseBy3Points.svg)](/index.php?title=File:Sketcher_CreateEllipseBy3Points.svg&filetimestamp=20240101170343&) [Ellipse by 3 points](/Sketcher_CreateEllipseBy3Points "Sketcher CreateEllipseBy3Points"): Creates an ellipse by the endpoints of one of its axes and a point along the ellipse. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): This is the same tool as [Ellipse by center](/Sketcher_CreateEllipseByCenter "Sketcher CreateEllipseByCenter") but with a different initial mode.

  * [![](/images/a/a2/Sketcher_CreateRectangle.svg)](/index.php?title=File:Sketcher_CreateRectangle.svg&filetimestamp=20240101090846&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) Create rectangle:

    

  * [![](/images/a/a2/Sketcher_CreateRectangle.svg)](/index.php?title=File:Sketcher_CreateRectangle.svg&filetimestamp=20240101090846&) [Rectangle](/Sketcher_CreateRectangle "Sketcher CreateRectangle"): Creates a rectangle. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): The tool has four modes. Rounded corners and creating an offset copy are optional features.

    

  * [![](/images/d/d3/Sketcher_CreateRectangle_Center.svg)](/index.php?title=File:Sketcher_CreateRectangle_Center.svg&filetimestamp=20240101090859&) [Centered rectangle](/Sketcher_CreateRectangle_Center "Sketcher CreateRectangle Center"): Creates a centered rectangle. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): This is the same tool as [Rectangle](/Sketcher_CreateRectangle "Sketcher CreateRectangle") but with a different initial mode.

    

  * [![](/images/e/ea/Sketcher_CreateOblong.svg)](/index.php?title=File:Sketcher_CreateOblong.svg&filetimestamp=20240101090600&) [Rounded rectangle](/Sketcher_CreateOblong "Sketcher CreateOblong"): Creates a rounded rectangle. Idem.

  * [![](/images/5/53/Sketcher_CreateHexagon.svg)](/index.php?title=File:Sketcher_CreateHexagon.svg&filetimestamp=20240101090346&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) Create regular polygon:

    

  * [![](/images/8/8d/Sketcher_CreateTriangle.svg)](/index.php?title=File:Sketcher_CreateTriangle.svg&filetimestamp=20240101091254&) [Triangle](/Sketcher_CreateTriangle "Sketcher CreateTriangle"): creates an equilateral triangle. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): This is the same tool as [Regular polygon](/Sketcher_CreateRegularPolygon "Sketcher CreateRegularPolygon") but with the number of sides preset to a specif value.

    

  * [![](/images/0/0c/Sketcher_CreateSquare.svg)](/index.php?title=File:Sketcher_CreateSquare.svg&filetimestamp=20240101091203&) [Square](/Sketcher_CreateSquare "Sketcher CreateSquare"): Creates a square. Idem.

    

  * [![](/images/2/25/Sketcher_CreatePentagon.svg)](/index.php?title=File:Sketcher_CreatePentagon.svg&filetimestamp=20240101090711&) [Pentagon](/Sketcher_CreatePentagon "Sketcher CreatePentagon"): Creates a pentagon. Idem.

    

  * [![](/images/5/53/Sketcher_CreateHexagon.svg)](/index.php?title=File:Sketcher_CreateHexagon.svg&filetimestamp=20240101090346&) [Hexagon](/Sketcher_CreateHexagon "Sketcher CreateHexagon"): Creates a hexagon. Idem.

    

  * [![](/images/3/34/Sketcher_CreateHeptagon.svg)](/index.php?title=File:Sketcher_CreateHeptagon.svg&filetimestamp=20240101090316&) [Heptagon](/Sketcher_CreateHeptagon "Sketcher CreateHeptagon"): Creates a heptagon. Idem.

    

  * [![](/images/1/12/Sketcher_CreateOctagon.svg)](/index.php?title=File:Sketcher_CreateOctagon.svg&filetimestamp=20240101090622&) [Octagon](/Sketcher_CreateOctagon "Sketcher CreateOctagon"): Creates an octagon. Idem.

    

  * [![](/images/2/2a/Sketcher_CreateRegularPolygon.svg)](/index.php?title=File:Sketcher_CreateRegularPolygon.svg&filetimestamp=20240101091103&) [Regular polygon](/Sketcher_CreateRegularPolygon "Sketcher CreateRegularPolygon"): Creates a regular polygon. The number of sides can be specified.

  * [![](/images/d/dd/Sketcher_CreateSlot.svg)](/index.php?title=File:Sketcher_CreateSlot.svg&filetimestamp=20240101091129&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) Create slot:

    

  * [![](/images/d/dd/Sketcher_CreateSlot.svg)](/index.php?title=File:Sketcher_CreateSlot.svg&filetimestamp=20240101091129&) [Slot](/Sketcher_CreateSlot "Sketcher CreateSlot"): Creates a slot.

    

  * [![](/images/a/a4/Sketcher_CreateArcSlot.svg)](/index.php?title=File:Sketcher_CreateArcSlot.svg&filetimestamp=20240101085806&) [Arc slot](/Sketcher_CreateArcSlot "Sketcher CreateArcSlot"): Creates an arc slot. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

  * [![](/images/4/41/Sketcher_CreateBSpline.svg)](/index.php?title=File:Sketcher_CreateBSpline.svg&filetimestamp=20240101085839&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) Create B-spline:

    

  * [![](/images/4/41/Sketcher_CreateBSpline.svg)](/index.php?title=File:Sketcher_CreateBSpline.svg&filetimestamp=20240101085839&) [B-spline by control points](/Sketcher_CreateBSpline "Sketcher CreateBSpline"): Creates a B-spline curve by control points. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): Or by knot points.

    

  * [![](/images/d/db/Sketcher_CreatePeriodicBSpline.svg)](/index.php?title=File:Sketcher_CreatePeriodicBSpline.svg&filetimestamp=20240101170403&) [Periodic B-spline by control points](/Sketcher_CreatePeriodicBSpline "Sketcher CreatePeriodicBSpline"): Creates a periodic (closed) B-spline curve by control points. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): This is the same tool as [B-spline by control points](/Sketcher_CreateBSpline "Sketcher CreateBSpline") but with a different initial mode.

    

  * [![](/images/1/1d/Sketcher_CreateBSplineByInterpolation.svg)](/index.php?title=File:Sketcher_CreateBSplineByInterpolation.svg&filetimestamp=20240520185146&) [B-spline by knots](/Sketcher_CreateBSplineByInterpolation "Sketcher CreateBSplineByInterpolation"): Creates a B-spline curve by knot points. Idem.

    

  * [![](/images/3/31/Sketcher_CreatePeriodicBSplineByInterpolation.svg)](/index.php?title=File:Sketcher_CreatePeriodicBSplineByInterpolation.svg&filetimestamp=20240405092810&) [Periodic B-spline by knots](/Sketcher_CreatePeriodicBSplineByInterpolation "Sketcher CreatePeriodicBSplineByInterpolation"): Creates a periodic (closed) B-spline curve by knot points. Idem.

  * [![](/images/5/54/Sketcher_ToggleConstruction.svg)](/index.php?title=File:Sketcher_ToggleConstruction.svg&filetimestamp=20240228175128&) [Toggle construction geometry](/Sketcher_ToggleConstruction "Sketcher ToggleConstruction"): Either toggles the geometry creation tools to/from construction mode, or toggles selected geometry to/from construction geometry.

### Sketcher constraints

These are tools for creating constraints. Some constraints require the use of
[Helper constraints](/Sketcher_helper_constraint "Sketcher helper
constraint").

  * [![](/images/2/24/Sketcher_Dimension.svg)](/index.php?title=File:Sketcher_Dimension.svg&filetimestamp=20240102162811&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) Dimensional constraints:

    

  * [![](/images/2/24/Sketcher_Dimension.svg)](/index.php?title=File:Sketcher_Dimension.svg&filetimestamp=20240102162811&) [Dimension](/Sketcher_Dimension "Sketcher Dimension"): Is the context-sensitive constraint tool of the Sketcher Workbench. Based on the current selection, it offers appropriate dimensional constraints, but also geometric constraints. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

    

  * [![](/images/9/91/Sketcher_ConstrainDistanceX.svg)](/index.php?title=File:Sketcher_ConstrainDistanceX.svg&filetimestamp=20240101173427&) [Horizontal distance](/Sketcher_ConstrainDistanceX "Sketcher ConstrainDistanceX"): Fixes the horizontal distance between two points or the endpoints of a line. If a single point is pre-selected, the distance is relative to the origin of the sketch.

    

  * [![](/images/e/e6/Sketcher_ConstrainDistanceY.svg)](/index.php?title=File:Sketcher_ConstrainDistanceY.svg&filetimestamp=20240101173443&) [Vertical distance](/Sketcher_ConstrainDistanceY "Sketcher ConstrainDistanceY"): Fixes the vertical distance between two points or the endpoints of a line. If a single point is pre-selected, the distance is relative to the origin of the sketch.

    

  * [![](/images/9/95/Sketcher_ConstrainDistance.svg)](/index.php?title=File:Sketcher_ConstrainDistance.svg&filetimestamp=20240101173515&) [Distance](/Sketcher_ConstrainDistance "Sketcher ConstrainDistance"): Fixes the length of a line, the distance between two points, the perpendicular distance between a point and a line; or, [introduced in 0.21](/Release_notes_0.21 "Release notes 0.21"), the distance between the edges of two circles or arcs, or between the edge of a circle or arc and a line; or, [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"), the length of an arc.

    

  * [![](/images/2/2e/Sketcher_ConstrainRadiam.svg)](/index.php?title=File:Sketcher_ConstrainRadiam.svg&filetimestamp=20240101173642&) [Auto radius/diameter](/Sketcher_ConstrainRadiam "Sketcher ConstrainRadiam"): Fixes the radius of arcs and B-spline weight circles, and the diameter of circles.

    

  * [![](/images/e/ee/Sketcher_ConstrainRadius.svg)](/index.php?title=File:Sketcher_ConstrainRadius.svg&filetimestamp=20240101173607&) [Radius](/Sketcher_ConstrainRadius "Sketcher ConstrainRadius"): Fixes the radius of circles, arcs and B-spline weight circles.

    

  * [![](/images/8/8c/Sketcher_ConstrainDiameter.svg)](/index.php?title=File:Sketcher_ConstrainDiameter.svg&filetimestamp=20240101173623&) [Diameter](/Sketcher_ConstrainDiameter "Sketcher ConstrainDiameter"): Fixes the diameter of circles and arcs.

    

  * [![](/images/3/33/Sketcher_ConstrainAngle.svg)](/index.php?title=File:Sketcher_ConstrainAngle.svg&filetimestamp=20240101173744&) [Angle](/Sketcher_ConstrainAngle "Sketcher ConstrainAngle"): Fixes the angle between two edges, the angle of a line with the horizontal axis of the sketch, or the aperture angle of a circular arc.

    

  * [![](/images/8/85/Sketcher_ConstrainLock.svg)](/index.php?title=File:Sketcher_ConstrainLock.svg&filetimestamp=20240101173404&) [Lock](/Sketcher_ConstrainLock "Sketcher ConstrainLock"): Applies [Horizontal distance](/Sketcher_ConstrainDistanceX "Sketcher ConstrainDistanceX") and [Vertical distance](/Sketcher_ConstrainDistanceY "Sketcher ConstrainDistanceY") constraints to points. If a single point is selected the constraints reference the origin of the sketch. If two or more points are selected the constraints reference the last point in the selection.

  * [![](/images/1/18/Sketcher_ConstrainCoincidentUnified.svg)](/index.php?title=File:Sketcher_ConstrainCoincidentUnified.svg&filetimestamp=20240106131932&) [Coincident (unified)](/Sketcher_ConstrainCoincidentUnified "Sketcher ConstrainCoincidentUnified"): Creates a coincident constraint between points, fixes points on edges or axes, or creates a concentric constraint. It combines the [Coincident](/Sketcher_ConstrainCoincident "Sketcher ConstrainCoincident") and [Point on object](/Sketcher_ConstrainPointOnObject "Sketcher ConstrainPointOnObject") tools. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

  * [![](/images/9/95/Sketcher_ConstrainCoincident.svg)](/index.php?title=File:Sketcher_ConstrainCoincident.svg&filetimestamp=20240101173005&) [Coincident](/Sketcher_ConstrainCoincident "Sketcher ConstrainCoincident"): Creates a coincident constraint between points, or a concentric constraint.

  * [![](/images/4/4c/Sketcher_ConstrainPointOnObject.svg)](/index.php?title=File:Sketcher_ConstrainPointOnObject.svg&filetimestamp=20240101173043&) [Point on object](/Sketcher_ConstrainPointOnObject "Sketcher ConstrainPointOnObject"): Fixes points on edges or axes.

  * [![](/images/b/b7/Sketcher_ConstrainHorVer.svg)](/index.php?title=File:Sketcher_ConstrainHorVer.svg&filetimestamp=20240102154008&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&)Horizontal/vertical constraints:

    

  * [![](/images/b/b7/Sketcher_ConstrainHorVer.svg)](/index.php?title=File:Sketcher_ConstrainHorVer.svg&filetimestamp=20240102154008&) [Horizontal/vertical](/Sketcher_ConstrainHorVer "Sketcher ConstrainHorVer"): Constrains lines or pairs of points to be horizontal or vertical, whichever is closest to the current alignment. It combines the [Horizontal](/Sketcher_ConstrainHorizontal "Sketcher ConstrainHorizontal") and [Vertical](/Sketcher_ConstrainVertical "Sketcher ConstrainVertical") tools. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

    

  * [![](/images/5/55/Sketcher_ConstrainHorizontal.svg)](/index.php?title=File:Sketcher_ConstrainHorizontal.svg&filetimestamp=20240101173125&) [Horizontal](/Sketcher_ConstrainHorizontal "Sketcher ConstrainHorizontal"): Constrains lines or pairs of points to be horizontal.

    

  * [![](/images/b/ba/Sketcher_ConstrainVertical.svg)](/index.php?title=File:Sketcher_ConstrainVertical.svg&filetimestamp=20240101173106&) [Vertical](/Sketcher_ConstrainVertical "Sketcher ConstrainVertical"): Constrains lines or pairs of points to be vertical.

  * [![](/images/1/1d/Sketcher_ConstrainParallel.svg)](/index.php?title=File:Sketcher_ConstrainParallel.svg&filetimestamp=20240101173144&) [Parallel](/Sketcher_ConstrainParallel "Sketcher ConstrainParallel"): Constrains lines to be parallel.

  * [![](/images/f/f9/Sketcher_ConstrainPerpendicular.svg)](/index.php?title=File:Sketcher_ConstrainPerpendicular.svg&filetimestamp=20240101173234&) [Perpendicular](/Sketcher_ConstrainPerpendicular "Sketcher ConstrainPerpendicular"): Constrains two lines to be perpendicular, or two edges, or an edge and an axis, to be perpendicular at their intersection. The constraint can also connect two edges, forcing them to be perpendicular at the joint.

  * [![](/images/e/ea/Sketcher_ConstrainTangent.svg)](/index.php?title=File:Sketcher_ConstrainTangent.svg&filetimestamp=20240101173249&) [Tangent or collinear](/Sketcher_ConstrainTangent "Sketcher ConstrainTangent"): Constrains two edges, or an edge and an axis, to be tangent. The constraint can also connect two edges, forcing them to be tangent at the joint. If two lines are selected they are made collinear.

  * [![](/images/c/cf/Sketcher_ConstrainEqual.svg)](/index.php?title=File:Sketcher_ConstrainEqual.svg&filetimestamp=20240101173306&) [Equal](/Sketcher_ConstrainEqual "Sketcher ConstrainEqual"): Constrains edges to have an equal length (lines) or curvature (other edges except B-splines).

  * [![](/images/0/08/Sketcher_ConstrainSymmetric.svg)](/index.php?title=File:Sketcher_ConstrainSymmetric.svg&filetimestamp=20240101173322&) [Symmetric](/Sketcher_ConstrainSymmetric "Sketcher ConstrainSymmetric"): Constrains two points to be symmetrical around a line or axis, or around a third point.

  * [![](/images/b/be/Sketcher_ConstrainBlock.svg)](/index.php?title=File:Sketcher_ConstrainBlock.svg&filetimestamp=20240101173347&) [Block](/Sketcher_ConstrainBlock "Sketcher ConstrainBlock"): Blocks edges in place with a single constraint. It is mainly intended for B-splines.

  * [![](/images/c/c7/Sketcher_ConstrainSnellsLaw.svg)](/index.php?title=File:Sketcher_ConstrainSnellsLaw.svg&filetimestamp=20240101173802&) [Refraction (Snell's law)](/Sketcher_ConstrainSnellsLaw "Sketcher ConstrainSnellsLaw"): Constrains two lines to follow the law of refraction of light as it penetrates through an interface.

  * [![](/images/d/d4/Sketcher_ToggleDrivingConstraint.svg)](/index.php?title=File:Sketcher_ToggleDrivingConstraint.svg&filetimestamp=20240101171305&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) Toggle constraints:

    

  * [![](/images/d/d4/Sketcher_ToggleDrivingConstraint.svg)](/index.php?title=File:Sketcher_ToggleDrivingConstraint.svg&filetimestamp=20240101171305&) [Toggle driving/reference constraint](/Sketcher_ToggleDrivingConstraint "Sketcher ToggleDrivingConstraint"): Toggles the dimensional constraint creation tools between driving and reference mode, or toggles selected dimensional constraints between those modes.

    

  * [![](/images/c/c7/Sketcher_ToggleActiveConstraint.svg)](/index.php?title=File:Sketcher_ToggleActiveConstraint.svg&filetimestamp=20231231200133&) [Activate/deactivate constraint](/Sketcher_ToggleActiveConstraint "Sketcher ToggleActiveConstraint"): Activates or deactivates selected constraints.

### Sketcher tools

  * [![](/images/6/63/Sketcher_CreateFillet.svg)](/index.php?title=File:Sketcher_CreateFillet.svg&filetimestamp=20240101090229&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) Create fillet/chamfer:

    

  * [![](/images/6/63/Sketcher_CreateFillet.svg)](/index.php?title=File:Sketcher_CreateFillet.svg&filetimestamp=20240101090229&) [Fillet](/Sketcher_CreateFillet "Sketcher CreateFillet"): Creates a fillet between two non-parallel edges. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): The tool can also create a chamfer.

    

  * [![](/images/9/95/Sketcher_CreateChamfer.svg)](/index.php?title=File:Sketcher_CreateChamfer.svg&filetimestamp=20240323210113&) [Chamfer](/Sketcher_CreateChamfer "Sketcher CreateChamfer"): creates a chamfer between two non-parallel edges. This is the same tool as [Fillet](/Sketcher_CreateFillet "Sketcher CreateFillet") but with a different initial mode. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

  * [![](/images/4/4e/Sketcher_Trimming.svg)](/index.php?title=File:Sketcher_Trimming.svg&filetimestamp=20240101091455&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) Edit edge:

    

  * [![](/images/4/4e/Sketcher_Trimming.svg)](/index.php?title=File:Sketcher_Trimming.svg&filetimestamp=20240101091455&) [Trim](/Sketcher_Trimming "Sketcher Trimming"): Trims an edge at the nearest intersections with other edges.

    

  * [![](/images/b/b7/Sketcher_Split.svg)](/index.php?title=File:Sketcher_Split.svg&filetimestamp=20240101091342&) [Split](/Sketcher_Split "Sketcher Split"): Splits an edge while transferring most constraints.

    

  * [![](/images/6/65/Sketcher_Extend.svg)](/index.php?title=File:Sketcher_Extend.svg&filetimestamp=20240101091319&) [Extend](/Sketcher_Extend "Sketcher Extend"): Extends or shortens a line or an arc to an arbitrary location, or to a target edge or point.

  * [![](/images/b/b2/Sketcher_External.svg)](/index.php?title=File:Sketcher_External.svg&filetimestamp=20240101091332&) [External geometry](/Sketcher_External "Sketcher External"): Projects edges and/or vertices belonging to objects outside the sketch onto the sketch plane. 1.0 and below

  * [![](/images/5/54/Sketcher_Projection.svg)](/index.php?title=File:Sketcher_Projection.svg&filetimestamp=20241129200338&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) External geometry:

    

  * [![](/images/5/54/Sketcher_Projection.svg)](/index.php?title=File:Sketcher_Projection.svg&filetimestamp=20241129200338&) [Create external projection geometry](/Sketcher_Projection "Sketcher Projection"): Creates the projection edges of external geometry. [introduced in 1.1](/Release_notes_1.1 "Release notes 1.1")

    

  * [![](/images/9/95/Sketcher_Intersection.svg)](/index.php?title=File:Sketcher_Intersection.svg&filetimestamp=20241129200334&) [Create external intersection geometry](/Sketcher_Intersection "Sketcher Intersection"): Creates the intersection edges of external geometry with the sketch plane. [introduced in 1.1](/Release_notes_1.1 "Release notes 1.1")

  * [![](/images/6/62/Sketcher_CarbonCopy.svg)](/index.php?title=File:Sketcher_CarbonCopy.svg&filetimestamp=20240719181043&) [Carbon copy](/Sketcher_CarbonCopy "Sketcher CarbonCopy"): Copies all geometry and constraints from another sketch into the active sketch.

  * [![](/images/7/71/Sketcher_SelectOrigin.svg)](/index.php?title=File:Sketcher_SelectOrigin.svg&filetimestamp=20240101115659&) [Select origin](/Sketcher_SelectOrigin "Sketcher SelectOrigin"): Selects the origin of the sketch.

  * [![](/images/9/9a/Sketcher_SelectHorizontalAxis.svg)](/index.php?title=File:Sketcher_SelectHorizontalAxis.svg&filetimestamp=20240101115648&) [Select horizontal axis](/Sketcher_SelectHorizontalAxis "Sketcher SelectHorizontalAxis"): Selects the horizontal axis of the sketch.

  * [![](/images/c/c1/Sketcher_SelectVerticalAxis.svg)](/index.php?title=File:Sketcher_SelectVerticalAxis.svg&filetimestamp=20240101115720&) [Select vertical axis](/Sketcher_SelectVerticalAxis "Sketcher SelectVerticalAxis"): Selects the vertical axis of the sketch.

  * [![](/images/b/b8/Sketcher_Translate.svg)](/index.php?title=File:Sketcher_Translate.svg&filetimestamp=20240222145016&) [Array transform](/Sketcher_Translate "Sketcher Translate"): Moves or optionally creates copies of selected elements. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

  * [![](/images/b/bc/Sketcher_Rotate.svg)](/index.php?title=File:Sketcher_Rotate.svg&filetimestamp=20240101115504&) [Polar transform](/Sketcher_Rotate "Sketcher Rotate"): Rotates or optionally creates rotated copies of selected elements. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

  * [![](/images/3/3e/Sketcher_Scale.svg)](/index.php?title=File:Sketcher_Scale.svg&filetimestamp=20240207133809&) [Scale transform](/Sketcher_Scale "Sketcher Scale"): Scales or optionally creates scaled copies of selected elements. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

  * [![](/images/e/e6/Sketcher_Offset.svg)](/index.php?title=File:Sketcher_Offset.svg&filetimestamp=20240101115402&) [Offset geometry](/Sketcher_Offset "Sketcher Offset"): Creates equidistant edges around selected edges. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

  * [![](/images/3/30/Sketcher_Symmetry.svg)](/index.php?title=File:Sketcher_Symmetry.svg&filetimestamp=20240101115730&) [Symmetry](/Sketcher_Symmetry "Sketcher Symmetry"): Creates mirrored copies of selected elements.

  * [![](/images/b/b1/Sketcher_RemoveAxesAlignment.svg)](/index.php?title=File:Sketcher_RemoveAxesAlignment.svg&filetimestamp=20240101115445&) [Remove axes alignment](/Sketcher_RemoveAxesAlignment "Sketcher RemoveAxesAlignment"): Removes the axes alignment of selected edges by replacing [Horizontal](/Sketcher_ConstrainHorizontal "Sketcher ConstrainHorizontal") and [Vertical](/Sketcher_ConstrainVertical "Sketcher ConstrainVertical") constraints with [Parallel](/Sketcher_ConstrainParallel "Sketcher ConstrainParallel") and [Perpendicular](/Sketcher_ConstrainPerpendicular "Sketcher ConstrainPerpendicular") constraints.

  * [![](/images/7/71/Sketcher_DeleteAllGeometry.svg)](/index.php?title=File:Sketcher_DeleteAllGeometry.svg&filetimestamp=20240101171728&) [Delete all geometry](/Sketcher_DeleteAllGeometry "Sketcher DeleteAllGeometry"): Deletes all geometry and all constraints from the sketch.

  * [![](/images/c/c5/Sketcher_DeleteAllConstraints.svg)](/index.php?title=File:Sketcher_DeleteAllConstraints.svg&filetimestamp=20240101171808&) [Delete all constraints](/Sketcher_DeleteAllConstraints "Sketcher DeleteAllConstraints"): Deletes all constraints from the sketch.

  * [![](/images/a/a2/Edit-copy.svg)](/index.php?title=File:Edit-copy.svg&filetimestamp=20240704192520&) Copy in Sketcher: See Copy, cut and paste.

  * [![](/images/8/88/Edit-cut.svg)](/index.php?title=File:Edit-cut.svg&filetimestamp=20240704192537&) Cut in Sketcher: See Copy, cut and paste.

  * [![](/images/8/83/Edit-paste.svg)](/index.php?title=File:Edit-paste.svg&filetimestamp=20240704192705&) Paste in Sketcher: See Copy, cut and paste.

### Sketcher B-spline tools

  * [![](/images/f/fe/Sketcher_BSplineConvertToNURBS.svg)](/index.php?title=File:Sketcher_BSplineConvertToNURBS.svg&filetimestamp=20240331101832&) [Convert geometry to B-spline](/Sketcher_BSplineConvertToNURBS "Sketcher BSplineConvertToNURBS"): Converts edges to B-splines.

  * [![](/images/9/9e/Sketcher_BSplineIncreaseDegree.svg)](/index.php?title=File:Sketcher_BSplineIncreaseDegree.svg&filetimestamp=20240101115116&) [Increase B-spline degree](/Sketcher_BSplineIncreaseDegree "Sketcher BSplineIncreaseDegree"): Increases the degree (order) of B-splines.

  * [![](/images/b/b1/Sketcher_BSplineDecreaseDegree.svg)](/index.php?title=File:Sketcher_BSplineDecreaseDegree.svg&filetimestamp=20240101115056&) [Decrease B-spline degree](/Sketcher_BSplineDecreaseDegree "Sketcher BSplineDecreaseDegree"): Decreases the degree (order) of B-splines.

  * [![](/images/2/2f/Sketcher_BSplineIncreaseKnotMultiplicity.svg)](/index.php?title=File:Sketcher_BSplineIncreaseKnotMultiplicity.svg&filetimestamp=20240101115126&) [Increase knot multiplicity](/Sketcher_BSplineIncreaseKnotMultiplicity "Sketcher BSplineIncreaseKnotMultiplicity"): Increases the multiplicity of a B-spline knot.

  * [![](/images/f/f1/Sketcher_BSplineDecreaseKnotMultiplicity.svg)](/index.php?title=File:Sketcher_BSplineDecreaseKnotMultiplicity.svg&filetimestamp=20240101115106&) [Decrease knot multiplicity](/Sketcher_BSplineDecreaseKnotMultiplicity "Sketcher BSplineDecreaseKnotMultiplicity"): Decreases the multiplicity of a B-spline knot.

  * [![](/images/6/60/Sketcher_BSplineInsertKnot.svg)](/index.php?title=File:Sketcher_BSplineInsertKnot.svg&filetimestamp=20240513165934&) [Insert knot](/Sketcher_BSplineInsertKnot "Sketcher BSplineInsertKnot"): Inserts a knot into a B-spline or increases the multiplicity of an existing knot.

  * [![](/images/5/5b/Sketcher_JoinCurves.svg)](/index.php?title=File:Sketcher_JoinCurves.svg&filetimestamp=20240513170116&) [Join curves](/Sketcher_JoinCurves "Sketcher JoinCurves"): Creates a B-spline by joining two existing B-splines or other edges. [introduced in 0.21](/Release_notes_0.21 "Release notes 0.21")

### Sketcher visual

  * [![](/images/8/83/Sketcher_SelectElementsWithDoFs.svg)](/index.php?title=File:Sketcher_SelectElementsWithDoFs.svg&filetimestamp=20240101115636&) [Select unconstrained DoF](/Sketcher_SelectElementsWithDoFs "Sketcher SelectElementsWithDoFs"): Selects the not fully constrained elements in the sketch.

  * [![](/images/7/7a/Sketcher_SelectConstraints.svg)](/index.php?title=File:Sketcher_SelectConstraints.svg&filetimestamp=20240101115612&) [Select associated constraints](/Sketcher_SelectConstraints "Sketcher SelectConstraints"): Selects the constraints associated with sketch elements.

  * [![](/images/2/23/Sketcher_SelectElementsAssociatedWithConstraints.svg)](/index.php?title=File:Sketcher_SelectElementsAssociatedWithConstraints.svg&filetimestamp=20240101115625&) [Select associated geometry](/Sketcher_SelectElementsAssociatedWithConstraints "Sketcher SelectElementsAssociatedWithConstraints"): Selects the sketch elements associated with constraints.

  * [![](/images/0/02/Sketcher_SelectRedundantConstraints.svg)](/index.php?title=File:Sketcher_SelectRedundantConstraints.svg&filetimestamp=20240101115710&) [Select redundant constraints](/Sketcher_SelectRedundantConstraints "Sketcher SelectRedundantConstraints"): Selects the redundant constraints in the sketch.

  * [![](/images/b/b5/Sketcher_SelectConflictingConstraints.svg)](/index.php?title=File:Sketcher_SelectConflictingConstraints.svg&filetimestamp=20240101115558&) [Select conflicting constraints](/Sketcher_SelectConflictingConstraints "Sketcher SelectConflictingConstraints"): Selects the conflicting constraints in the sketch.

  * [![](/images/0/07/Sketcher_ArcOverlay.svg)](/index.php?title=File:Sketcher_ArcOverlay.svg&filetimestamp=20240101112838&) [Show/hide circular helper for arcs](/Sketcher_ArcOverlay "Sketcher ArcOverlay"): Shows or hides the circular helpers (underlying virtual circles) for arcs in all sketches. [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

  * [![](/images/7/73/Sketcher_BSplinePolygon.svg)](/index.php?title=File:Sketcher_BSplinePolygon.svg&filetimestamp=20240101113010&)[![](/images/3/34/Toolbar_flyout_arrow_blue_background.svg)](/index.php?title=File:Toolbar_flyout_arrow_blue_background.svg&filetimestamp=20221006081506&) Show/hide B-spline information layer:

    

  * [![](/images/3/36/Sketcher_BSplineDegree.svg)](/index.php?title=File:Sketcher_BSplineDegree.svg&filetimestamp=20240101112910&) [Show/hide B-spline degree](/Sketcher_BSplineDegree "Sketcher BSplineDegree"): Shows or hides the B-spline degree in all sketches.

    

  * [![](/images/7/73/Sketcher_BSplinePolygon.svg)](/index.php?title=File:Sketcher_BSplinePolygon.svg&filetimestamp=20240101113010&) [Show/hide B-spline control polygon](/Sketcher_BSplinePolygon "Sketcher BSplinePolygon"): Shows or hides the B-spline control polygon in all sketches.

    

  * [![](/images/5/50/Sketcher_BSplineComb.svg)](/index.php?title=File:Sketcher_BSplineComb.svg&filetimestamp=20240101112854&) [Show/hide B-spline curvature comb](/Sketcher_BSplineComb "Sketcher BSplineComb"): Shows or hides the B-spline curvature comb in all sketches.

    

  * [![](/images/1/17/Sketcher_BSplineKnotMultiplicity.svg)](/index.php?title=File:Sketcher_BSplineKnotMultiplicity.svg&filetimestamp=20240101112934&) [Show/hide B-spline knot multiplicity](/Sketcher_BSplineKnotMultiplicity "Sketcher BSplineKnotMultiplicity"): Shows or hides the B-spline knot multiplicity in all sketches.

    

  * [![](/images/d/da/Sketcher_BSplinePoleWeight.svg)](/index.php?title=File:Sketcher_BSplinePoleWeight.svg&filetimestamp=20240101112951&) [Show/hide B-spline control point weight](/Sketcher_BSplinePoleWeight "Sketcher BSplinePoleWeight"): Shows or hides the B-spline control point weight in all sketches.

  * [![](/images/1/1a/Sketcher_RestoreInternalAlignmentGeometry.svg)](/index.php?title=File:Sketcher_RestoreInternalAlignmentGeometry.svg&filetimestamp=20240101171622&) [Show/hide internal geometry](/Sketcher_RestoreInternalAlignmentGeometry "Sketcher RestoreInternalAlignmentGeometry"): Deletes the internal geometry of elements, or recreates missing internal geometry.

  * [![](/images/4/4a/Sketcher_SwitchVirtualSpace.svg)](/index.php?title=File:Sketcher_SwitchVirtualSpace.svg&filetimestamp=20231231201841&) [Switch virtual space](/Sketcher_SwitchVirtualSpace "Sketcher SwitchVirtualSpace"): (un)hides constraints or switches the visible virtual space.

### Obsolete tools

  * [![](/images/c/ce/Sketcher_Clone.svg)](/index.php?title=File:Sketcher_Clone.svg&filetimestamp=20240101115259&) [Clone](/Sketcher_Clone "Sketcher Clone"): Clones a Sketcher element. Not available in 1.0 and above.

  * [![](/images/b/be/Sketcher_CloseShape.svg)](/index.php?title=File:Sketcher_CloseShape.svg&filetimestamp=20170323164507&) [Close shape](/Sketcher_CloseShape "Sketcher CloseShape"): Creates a closed shape by applying coincident constraints to endpoints. Not available in 0.21 and above.

  * [![](/images/3/38/Sketcher_CreatePointFillet.svg)](/index.php?title=File:Sketcher_CreatePointFillet.svg&filetimestamp=20240101090747&) [Corner-preserving fillet](/Sketcher_CreatePointFillet "Sketcher CreatePointFillet"): Creates a fillet between two non-parallel lines while preserving their corner point. Not available in 1.0 and above.

  * [![](/images/8/8a/Sketcher_ConnectLines.svg)](/index.php?title=File:Sketcher_ConnectLines.svg&filetimestamp=20170323164544&) [Connect edges](/Sketcher_ConnectLines "Sketcher ConnectLines"): Connect Sketcher elements by applying coincident constraints to endpoints. Not available in 0.21 and above.

  * [![](/images/6/66/Sketcher_Copy.svg)](/index.php?title=File:Sketcher_Copy.svg&filetimestamp=20240101115313&) [Copy](/Sketcher_Copy "Sketcher Copy"): Copies a Sketcher element. Not available in 1.0 and above.

  * [![](/images/8/8d/Sketcher_Move.svg)](/index.php?title=File:Sketcher_Move.svg&filetimestamp=20240101115349&) [Move](/Sketcher_Move "Sketcher Move"): Moves the selected geometry taking as reference the last selected point. Not available in 1.0 and above.

  * [![](/images/5/51/Sketcher_RectangularArray.svg)](/index.php?title=File:Sketcher_RectangularArray.svg&filetimestamp=20240101115435&) [Rectangular array](/Sketcher_RectangularArray "Sketcher RectangularArray"): Creates an array of selected Sketcher elements. Not available in 1.0 and above.

## Preferences

  * [![](/images/9/91/Workbench_Sketcher.svg)](/index.php?title=File:Workbench_Sketcher.svg&filetimestamp=20231231194727&) [Preferences](/Sketcher_Preferences "Sketcher Preferences"): Preferences for the Sketcher Workbench.

## Drawing aids

The Sketcher Workbench has several drawing aids and other features that can
help when creating geometry and applying constraints.

### Continue modes

There are two continue modes: **Geometry creation "Continue Mode"** and
**Constraint creation "Continue Mode"**. If these are checked (default) in the
[preferences](/Sketcher_Preferences#Display "Sketcher Preferences"), related
tools will restart after finishing. To exit a continuous tool press Esc or the
right mouse button. This must be repeated if a continuous geometry tool has
already received input. You can also exit a continuous tool by starting
another geometry or constraint creation tool. Note that pressing Esc if no
tool is active will exit sketch edit mode. Uncheck the **Esc can leave sketch
edit mode** [preference](/Sketcher_Preferences#General "Sketcher Preferences")
if you often inadvertently press Esc too many times.

### Auto constraints

In sketches that have **Auto constraints** checked (default) several
constraints are applied automatically. The icon of a proposed automatic
constraint is shown next to the cursor when it is placed correctly. Left-
clicking will then apply that constraint. This is a per-sketch setting that
can be changed in the [Sketcher Dialog](/Sketcher_Dialog#Constraints "Sketcher
Dialog") or by changing the View**Autoconstraints**
[property](/Property_editor "Property editor") of the sketch.

The following constraints are applied automatically:

  * [![](/images/9/95/Sketcher_ConstrainCoincident.svg)](/index.php?title=File:Sketcher_ConstrainCoincident.svg&filetimestamp=20240101173005&) [Coincident](/Sketcher_ConstrainCoincident "Sketcher ConstrainCoincident")
  * [![](/images/4/4c/Sketcher_ConstrainPointOnObject.svg)](/index.php?title=File:Sketcher_ConstrainPointOnObject.svg&filetimestamp=20240101173043&) [Point on object](/Sketcher_ConstrainPointOnObject "Sketcher ConstrainPointOnObject")
  * [![](/images/5/55/Sketcher_ConstrainHorizontal.svg)](/index.php?title=File:Sketcher_ConstrainHorizontal.svg&filetimestamp=20240101173125&) [Horizontal](/Sketcher_ConstrainHorizontal "Sketcher ConstrainHorizontal")
  * [![](/images/b/ba/Sketcher_ConstrainVertical.svg)](/index.php?title=File:Sketcher_ConstrainVertical.svg&filetimestamp=20240101173106&) [Vertical](/Sketcher_ConstrainVertical "Sketcher ConstrainVertical")
  * [![](/images/e/ea/Sketcher_ConstrainTangent.svg)](/index.php?title=File:Sketcher_ConstrainTangent.svg&filetimestamp=20240101173249&) [Tangent](/Sketcher_ConstrainTangent "Sketcher ConstrainTangent")
  * [introduced in 1.0](/Release_notes_1.0 "Release notes 1.0"): [![](/images/0/08/Sketcher_ConstrainSymmetric.svg)](/index.php?title=File:Sketcher_ConstrainSymmetric.svg&filetimestamp=20240101173322&) [Symmetric](/Sketcher_ConstrainSymmetric "Sketcher ConstrainSymmetric") (line midpoint)

### Snapping

[introduced in 0.21](/Release_notes_0.21 "Release notes 0.21")

It is possible to [snap](/Sketcher_Snap "Sketcher Snap") to grid lines and
grid intersection, to edges of geometry and midpoints of lines and arcs, and
to certain angles. Please note that snapping does not produce constraints in
and of itself. For example, only if Auto constraints is switched on will
snapping to an edge produce a [Point on object
constraint](/Sketcher_ConstrainPointOnObject "Sketcher
ConstrainPointOnObject"). But just picking a point on the edge would then have
the same result.

### On-View-Parameters

[introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

Depending on the selected option in the
[preferences](/Sketcher_Preferences#General "Sketcher Preferences") only the
dimensional On-View-Parameters or both the dimensional and the positional On-
View-Parameters can be enabled. Positional parameters allow the input of exact
coordinates, for example the center of a circle, or the start point of a line.
Dimensional parameters allow the input of exact dimensions, for example the
radius of a circle, or the length and angle of a line. On-View-Parameters are
not available for all tools.

[![](/images/e/e6/Sketcher_On_view_parameters_positional.png)](/index.php?title=File:Sketcher_On_view_parameters_positional.png&filetimestamp=20240203203414&)

Determining the center point of a circle with the positional parameters
enabled

[![](/images/c/cc/Sketcher_On_view_parameters_dimensional.png)](/index.php?title=File:Sketcher_On_view_parameters_dimensional.png&filetimestamp=20240203203400&)

Determining the radius of a circle with the dimensional parameters enabled

If values are entered and confirmed by pressing Enter or Tab, related
constraints are added automatically. If two parameters are displayed at the
same time, for example the X and Y coordinate of a point, it is possible to
enter one value and pick a point to define the other. Depending on the object
additional constraints may be required to fully constrain it. Constraints
resulting from On-View-Parameters take precedence over those that may result
from [Auto constraints](/Sketcher_Dialog#Constraints "Sketcher Dialog").

[![](/images/thumb/6/69/Sketcher_ArcExample3.png/300px-
Sketcher_ArcExample3.png)](/index.php?title=File:Sketcher_ArcExample3.png&filetimestamp=20240130140506&)

Arc created by entering all On-View-Parameters with resulting automatically
created constraints

### Coordinate display

If the **Show coordinates beside cursor while editing**
[preference](/Sketcher_Preferences#Display "Sketcher Preferences") is checked
(default), the parameters of the current geometry tool (coordinates, radius,
or length and angle) are displayed next to the cursor. This is deactivated
while On-View-Parameters are shown.

## Selection methods

While a sketch is in edit mode the following selection methods can be used:

### 3D view element selection

As elsewhere in FreeCAD, an element can be selected in the [3D view](/3D_view
"3D view") with a single left mouse click. But there is no need to hold down
the Ctrl key when selecting multiple elements. Holding down that key is
possible though and has the advantage that you can miss-click without losing
the selection. Edges, points and constraints can be selected in this manner.

### 3D view box selection

Box selection in the 3D view works without using [Std
BoxSelection](/Std_BoxSelection "Std BoxSelection") or [Std
BoxElementSelection](/Std_BoxElementSelection "Std BoxElementSelection"):

  1. Make sure that no tool is active.
  2. Do one of the following: 
     * Click in an empty area and drag a rectangle from left to right to select elements that lie completely inside the rectangle.
     * Click in an empty area and drag a rectangle from right to left to also select elements that touch or cross the rectangle.

You can box-select edges and points, constraints cannot be box-selected.

### 3D view connected geometry selection

[introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

Double-clicking an edge in the 3D view will select all edges directly and
indirectly connected with that edge via endpoints. There is no need for the
edges to be connected with [Coincident
constraints](/Sketcher_ConstrainCoincident "Sketcher ConstrainCoincident"),
endpoints need only have the same coordinates.

### Sketcher Dialog selection

Edges and points can also be selected from the Elements section of the
[Sketcher Dialog](/Sketcher_Dialog "Sketcher Dialog"), and constraints from
the Constraints section of that dialog.

## Copy, cut and paste

[introduced in 1.0](/Release_notes_1.0 "Release notes 1.0")

The standard keyboard shortcuts, Ctrl+C, Ctrl+X and Ctrl+V, can be used to
copy, cut and paste selected Sketcher geometry including related constraints.
But these tools are also available from the **Sketch → Sketcher tools** menu.
They can be used within the same sketch but also between different sketches or
separate instances of FreeCAD. Since the data is copied to the clipboard in
the form of Python code, it can be used in other ways too (e.g. shared on the
forum).

## Best practices

Every CAD user develops their own way of working over time, but there are some
useful general principles to follow.

  * A series of simple sketches is easier to manage than a single complex one. For example, a first sketch can be created for the base 3D feature (either a pad or a revolve), while a second one can contain holes or cutouts (pockets). Some details can be left out, to be realized later on as 3D features. You can choose to avoid fillets in your sketch if there are too many, and add them as a 3D feature.
  * Always create a closed profile, or your sketch won't produce a solid, but rather a set of open faces. If you don't want some of the objects to be included in the solid creation, turn them to construction elements with the Construction Mode tool.
  * Use the Auto constraints feature to limit the number of constraints you'll have to add manually.
  * As a general rule, apply geometric constraints first, then dimensional constraints, and lock your sketch last. But remember: rules are made to be broken. If you're having trouble manipulating your sketch, it may be useful to constrain a few objects first before completing your profile.
  * If possible, center your sketch at the origin (0,0) with the Lock constraint. If your sketch is not symmetric, locate one of its points at the origin, or choose nice round numbers for the lock distances.
  * If you have the possibility to choose between the Length constraint and the Horizontal or Vertical distance constraints, prefer the latter. Horizontal and Vertical distance constraints are computationally cheaper.
  * In general, the best constraints to use are: Horizontal and Vertical constraints; Horizontal and Vertical distance constraints; point-to-point Tangency. If possible, limit the use of these: the general Length constraint; edge-to-edge Tangency; Point on object constraint; Symmetric constraint.
  * If in doubt about the validity of a sketch once it is complete (features turn green), close the Sketcher dialog and use [![](/images/d/d3/Sketcher_ValidateSketch.svg)](/index.php?title=File:Sketcher_ValidateSketch.svg&filetimestamp=20231231201854&) [Validate sketch](/Sketcher_ValidateSketch "Sketcher ValidateSketch").

## Flipping

The phenomenon that a fully constrained sketch, usually after a major change
to one of its dimensions, reaches an unintended new state is know as
"flipping". In the example below, changing one dimension completely changes
the shape of the sketch. Note that the sketch with the new shape is still
fully constrained.

[![](/images/thumb/5/5f/Sketcher_Flipping_Equal_Constraints.png/300px-
Sketcher_Flipping_Equal_Constraints.png)](/index.php?title=File:Sketcher_Flipping_Equal_Constraints.png&filetimestamp=20250805174536&)
[![](/images/thumb/3/36/Sketcher_Flipping_Equal_Constraints_Flipped.png/300px-
Sketcher_Flipping_Equal_Constraints_Flipped.png)](/index.php?title=File:Sketcher_Flipping_Equal_Constraints_Flipped.png&filetimestamp=20250805174608&)

Original sketch (left), and the same sketch after increasing the 20mm value to
1000mm (right)

### Methods to reduce flipping

#### Change dimensions in small increments

This is not always practical, but changing dimension values in smaller
increments can work.

#### Use a different solver

The LevenbergMarquardt solver, which is not the default solver, is known to be
less prone to flipping. See [Sketcher
Dialog](/Sketcher_Dialog#Advanced_solver_control "Sketcher Dialog") for more
information.

#### Use horizontal and vertical dimensions

[![](/images/thumb/b/bf/Sketcher_Flipping_HorVer_Dimensions.png/300px-
Sketcher_Flipping_HorVer_Dimensions.png)](/index.php?title=File:Sketcher_Flipping_HorVer_Dimensions.png&filetimestamp=20250805174627&)

Using [horizontal](/Sketcher_ConstrainDistanceX "Sketcher ConstrainDistanceX")
and [vertical dimensions](/Sketcher_ConstrainDistanceY "Sketcher
ConstrainDistanceY") instead of [equal](/Sketcher_ConstrainEqual "Sketcher
ConstrainEqual") constraints can prevent flipping. Points constrained by these
dimensions will not switch places. In the image above the added (orange)
dimensional constraints are linked to the original dimensions via
[expressions](/Expressions "Expressions").

#### Use angular dimensions

[![](/images/thumb/6/6e/Sketcher_Flipping_Angular_Dimensions.png/300px-
Sketcher_Flipping_Angular_Dimensions.png)](/index.php?title=File:Sketcher_Flipping_Angular_Dimensions.png&filetimestamp=20250805174512&)

Using [angular](/Sketcher_ConstrainAngle "Sketcher ConstrainAngle") dimensions
instead of [horizontal](/Sketcher_ConstrainHorizontal "Sketcher
ConstrainHorizontal") and [vertical](/Sketcher_ConstrainVertical "Sketcher
ConstrainVertical") constraints can also work. The angle between edges
constrained by angular dimensions will not change. 180° will not become 0°,
90° will not become 270°, etc. In the image all horizontal and vertical
constraints have been replaced, but just replacing two is already effective
here.

## Tutorials

  * [Sketcher Lecture](https://forum.freecad.org/viewtopic.php?f=36&t=30104) by chrisb. This is a more than 80 page PDF document that serves as a detailed manual for the Sketcher. It explains the basics of Sketcher usage, and goes into a lot of detail about the creation of geometrical shapes, and each of the constraints.
  * [Basic Sketcher Tutorial](/Basic_Sketcher_Tutorial "Basic Sketcher Tutorial") for beginners
  * [Sketcher Micro Tutorial - Constraint Practices](/Sketcher_Micro_Tutorial_-_Constraint_Practices "Sketcher Micro Tutorial - Constraint Practices")
  * [Sketcher requirement for a sketch](/Sketcher_requirement_for_a_sketch "Sketcher requirement for a sketch") Minimum requirement for a sketch and Complete determination of a sketch

## Scripting

The [Sketcher scripting](/Sketcher_scripting "Sketcher scripting") page
contains examples on how to create constraints from Python scripts.

## Examples

For some ideas of what can be achieved with Sketcher tools, have a look at:
[Sketcher examples](/Sketcher_Examples "Sketcher Examples").

![](/images/thumb/2/26/Sketcher_ExampleHinge-01.gif/80px-
Sketcher_ExampleHinge-01.gif)
![](/images/thumb/e/e0/Sketcher_ExampleHinge-15.png/90px-
Sketcher_ExampleHinge-15.png)

  

![](/images/6/6f/Arrow-left.svg) ![](/images/e/e3/Workbench_Robot.svg) [Robot
Workbench](/Robot_Workbench "Robot Workbench")

![](/images/b/be/Workbench_Spreadsheet.svg) [Spreadsheet
Workbench](/Spreadsheet_Workbench "Spreadsheet Workbench")
![](/images/a/af/Arrow-right.svg)

[Index](/Online_Help_Toc "Online Help Toc")
![](/images/7/76/Online_Help_Toc.svg)

Expand[![](/images/9/91/Workbench_Sketcher.svg)](/index.php?title=File:Workbench_Sketcher.svg&filetimestamp=20231231194727&)
Sketcher

  * **General:** [Create sketch](/Sketcher_NewSketch "Sketcher NewSketch"), [Edit sketch](/Sketcher_EditSketch "Sketcher EditSketch"), [Attach sketch](/Sketcher_MapSketch "Sketcher MapSketch"), [Reorient sketch](/Sketcher_ReorientSketch "Sketcher ReorientSketch"), [Validate sketch](/Sketcher_ValidateSketch "Sketcher ValidateSketch"), [Merge sketches](/Sketcher_MergeSketches "Sketcher MergeSketches"), [Mirror sketch](/Sketcher_MirrorSketch "Sketcher MirrorSketch"), [Leave sketch](/Sketcher_LeaveSketch "Sketcher LeaveSketch"), [View sketch](/Sketcher_ViewSketch "Sketcher ViewSketch"), [View section](/Sketcher_ViewSection "Sketcher ViewSection"), [Toggle grid](/Sketcher_Grid "Sketcher Grid"), [Toggle snap](/Sketcher_Snap "Sketcher Snap"), [Configure rendering order](/Sketcher_RenderingOrder "Sketcher RenderingOrder"), [Stop operation](/Sketcher_StopOperation "Sketcher StopOperation")

* * *

  * **Sketcher geometries:** [Point](/Sketcher_CreatePoint "Sketcher CreatePoint"), [Polyline](/Sketcher_CreatePolyline "Sketcher CreatePolyline"), [Line](/Sketcher_CreateLine "Sketcher CreateLine"), [Arc](/Sketcher_CreateArc "Sketcher CreateArc"), [Arc by 3 points](/Sketcher_Create3PointArc "Sketcher Create3PointArc"), [Arc of ellipse](/Sketcher_CreateArcOfEllipse "Sketcher CreateArcOfEllipse"), [Arc of hyperbola](/Sketcher_CreateArcOfHyperbola "Sketcher CreateArcOfHyperbola"), [Arc of parabola](/Sketcher_CreateArcOfParabola "Sketcher CreateArcOfParabola"), [Circle](/Sketcher_CreateCircle "Sketcher CreateCircle"), [Circle by 3 points](/Sketcher_Create3PointCircle "Sketcher Create3PointCircle"), [Ellipse](/Sketcher_CreateEllipseByCenter "Sketcher CreateEllipseByCenter"), [Ellipse by 3 points](/Sketcher_CreateEllipseBy3Points "Sketcher CreateEllipseBy3Points"), [Rectangle](/Sketcher_CreateRectangle "Sketcher CreateRectangle"), [Centered rectangle](/Sketcher_CreateRectangle_Center "Sketcher CreateRectangle Center"), [Rounded rectangle](/Sketcher_CreateOblong "Sketcher CreateOblong"), [Triangle](/Sketcher_CreateTriangle "Sketcher CreateTriangle"), [Square](/Sketcher_CreateSquare "Sketcher CreateSquare"), [Pentagon](/Sketcher_CreatePentagon "Sketcher CreatePentagon"), [Hexagon](/Sketcher_CreateHexagon "Sketcher CreateHexagon"), [Heptagon](/Sketcher_CreateHeptagon "Sketcher CreateHeptagon"), [Octagon](/Sketcher_CreateOctagon "Sketcher CreateOctagon"), [Regular polygon](/Sketcher_CreateRegularPolygon "Sketcher CreateRegularPolygon"), [Slot](/Sketcher_CreateSlot "Sketcher CreateSlot"), [Arc slot](/Sketcher_CreateArcSlot "Sketcher CreateArcSlot"), [B-spline by control points](/Sketcher_CreateBSpline "Sketcher CreateBSpline"), [Periodic B-spline by control points](/Sketcher_CreatePeriodicBSpline "Sketcher CreatePeriodicBSpline"), [B-spline by knots](/Sketcher_CreateBSplineByInterpolation "Sketcher CreateBSplineByInterpolation"), [Periodic B-spline by knots](/Sketcher_CreatePeriodicBSplineByInterpolation "Sketcher CreatePeriodicBSplineByInterpolation"), [Toggle construction geometry](/Sketcher_ToggleConstruction "Sketcher ToggleConstruction")

* * *

  * **Sketcher constraints:**
    * **Dimensional constraints:** [Dimension](/Sketcher_Dimension "Sketcher Dimension"), [Horizontal distance](/Sketcher_ConstrainDistanceX "Sketcher ConstrainDistanceX"), [Vertical distance](/Sketcher_ConstrainDistanceY "Sketcher ConstrainDistanceY"), [Distance](/Sketcher_ConstrainDistance "Sketcher ConstrainDistance"), [Auto radius/diameter](/Sketcher_ConstrainRadiam "Sketcher ConstrainRadiam"), [Radius](/Sketcher_ConstrainRadius "Sketcher ConstrainRadius"), [Diameter](/Sketcher_ConstrainDiameter "Sketcher ConstrainDiameter"), [Angle](/Sketcher_ConstrainAngle "Sketcher ConstrainAngle"), [Lock](/Sketcher_ConstrainLock "Sketcher ConstrainLock")
    * **Geometric constraints:** [Coincident (unified)](/Sketcher_ConstrainCoincidentUnified "Sketcher ConstrainCoincidentUnified"), [Coincident](/Sketcher_ConstrainCoincident "Sketcher ConstrainCoincident"), [Point on object](/Sketcher_ConstrainPointOnObject "Sketcher ConstrainPointOnObject"), [Horizontal/vertical](/Sketcher_ConstrainHorVer "Sketcher ConstrainHorVer"), [Horizontal](/Sketcher_ConstrainHorizontal "Sketcher ConstrainHorizontal"), [Vertical](/Sketcher_ConstrainVertical "Sketcher ConstrainVertical"), [Parallel](/Sketcher_ConstrainParallel "Sketcher ConstrainParallel"), [Perpendicular](/Sketcher_ConstrainPerpendicular "Sketcher ConstrainPerpendicular"), [Tangent or collinear](/Sketcher_ConstrainTangent "Sketcher ConstrainTangent"), [Equal](/Sketcher_ConstrainEqual "Sketcher ConstrainEqual"), [Symmetric](/Sketcher_ConstrainSymmetric "Sketcher ConstrainSymmetric"), [Block](/Sketcher_ConstrainBlock "Sketcher ConstrainBlock")
    * **Other constraints:** [Refraction (Snell's law)](/Sketcher_ConstrainSnellsLaw "Sketcher ConstrainSnellsLaw")
    * **Constraint tools:** [Toggle driving/reference constraint](/Sketcher_ToggleDrivingConstraint "Sketcher ToggleDrivingConstraint"), [Activate/deactivate constraint](/Sketcher_ToggleActiveConstraint "Sketcher ToggleActiveConstraint")

* * *

  * **Sketcher tools:** [Fillet](/Sketcher_CreateFillet "Sketcher CreateFillet"), [Chamfer](/Sketcher_CreateChamfer "Sketcher CreateChamfer"), [Trim](/Sketcher_Trimming "Sketcher Trimming"), [Split](/Sketcher_Split "Sketcher Split"), [Extend](/Sketcher_Extend "Sketcher Extend"), [External geometry](/Sketcher_External "Sketcher External"), [Carbon copy](/Sketcher_CarbonCopy "Sketcher CarbonCopy"), [Select origin](/Sketcher_SelectOrigin "Sketcher SelectOrigin"), [Select horizontal axis](/Sketcher_SelectHorizontalAxis "Sketcher SelectHorizontalAxis"), [Select vertical axis](/Sketcher_SelectVerticalAxis "Sketcher SelectVerticalAxis"), [Array transform](/Sketcher_Translate "Sketcher Translate"), [Polar transform](/Sketcher_Rotate "Sketcher Rotate"), [Scale transform](/Sketcher_Scale "Sketcher Scale"), [Offset geometry](/Sketcher_Offset "Sketcher Offset"), [Symmetry](/Sketcher_Symmetry "Sketcher Symmetry"), [Remove axes alignment](/Sketcher_RemoveAxesAlignment "Sketcher RemoveAxesAlignment"), [Delete all geometry](/Sketcher_DeleteAllGeometry "Sketcher DeleteAllGeometry"), [Delete all constraints](/Sketcher_DeleteAllConstraints "Sketcher DeleteAllConstraints")

* * *

  * **Sketcher B-spline tools:** [Convert geometry to B-spline](/Sketcher_BSplineConvertToNURBS "Sketcher BSplineConvertToNURBS"), [Increase B-spline degree](/Sketcher_BSplineIncreaseDegree "Sketcher BSplineIncreaseDegree"), [Decrease B-spline degree](/Sketcher_BSplineDecreaseDegree "Sketcher BSplineDecreaseDegree"), [Increase knot multiplicity](/Sketcher_BSplineIncreaseKnotMultiplicity "Sketcher BSplineIncreaseKnotMultiplicity"), [Decrease knot multiplicity](/Sketcher_BSplineDecreaseKnotMultiplicity "Sketcher BSplineDecreaseKnotMultiplicity"), [Insert knot](/Sketcher_BSplineInsertKnot "Sketcher BSplineInsertKnot"), [Join curves](/Sketcher_JoinCurves "Sketcher JoinCurves")

* * *

  * **Sketcher visual:** [Select unconstrained DoF](/Sketcher_SelectElementsWithDoFs "Sketcher SelectElementsWithDoFs"), [Select associated constraints](/Sketcher_SelectConstraints "Sketcher SelectConstraints"), [Select associated geometry](/Sketcher_SelectElementsAssociatedWithConstraints "Sketcher SelectElementsAssociatedWithConstraints"), [Select redundant constraints](/Sketcher_SelectRedundantConstraints "Sketcher SelectRedundantConstraints"), [Select conflicting constraints](/Sketcher_SelectConflictingConstraints "Sketcher SelectConflictingConstraints"), [Show/hide circular helper for arcs](/Sketcher_ArcOverlay "Sketcher ArcOverlay"), [Show/hide B-spline degree](/Sketcher_BSplineDegree "Sketcher BSplineDegree"), [Show/hide B-spline control polygon](/Sketcher_BSplinePolygon "Sketcher BSplinePolygon"), [Show/hide B-spline curvature comb](/Sketcher_BSplineComb "Sketcher BSplineComb"), [Show/hide B-spline knot multiplicity](/Sketcher_BSplineKnotMultiplicity "Sketcher BSplineKnotMultiplicity"), [Show/hide B-spline control point weight](/Sketcher_BSplinePoleWeight "Sketcher BSplinePoleWeight"), [Show/hide internal geometry](/Sketcher_RestoreInternalAlignmentGeometry "Sketcher RestoreInternalAlignmentGeometry"), [Switch virtual space](/Sketcher_SwitchVirtualSpace "Sketcher SwitchVirtualSpace")

* * *

  * **Additional:** [Sketcher Dialog](/Sketcher_Dialog "Sketcher Dialog"), [Preferences](/Sketcher_Preferences "Sketcher Preferences"), [Sketcher scripting](/Sketcher_scripting "Sketcher scripting")

Expand[![](/images/thumb/9/94/User_hub.png/24px-
User_hub.png)](/index.php?title=File:User_hub.png&filetimestamp=20190221145008&)
[User documentation](/User_hub "User hub")

  * **[Getting started](/Getting_started "Getting started")**
  * **Installation:** [Download](/Download "Download"), [Windows](/Installing_on_Windows "Installing on Windows"), [Linux](/Installing_on_Linux "Installing on Linux"), [Mac](/Installing_on_Mac "Installing on Mac"), [Additional components](/Installing_additional_components "Installing additional components"), [Docker](/Compile_on_Docker "Compile on Docker"), [AppImage](/AppImage "AppImage"), [Ubuntu Snap](/Ubuntu_Snap "Ubuntu Snap")
  * **Basics:** [About FreeCAD](/About_FreeCAD "About FreeCAD"), [Interface](/Interface "Interface"), [Mouse navigation](/Mouse_navigation "Mouse navigation"), [Selection methods](/Selection_methods "Selection methods"), [Object name](/Object_name "Object name"), [Preferences](/Preferences_Editor "Preferences Editor"), [Workbenches](/Workbenches "Workbenches"), [Document structure](/Document_structure "Document structure"), [Properties](/Property "Property"), [Help FreeCAD](/Help_FreeCAD "Help FreeCAD"), [Donate](/Donate "Donate")

* * *

  * **Help:** [Tutorials](/Tutorials "Tutorials"), [Video tutorials](/Video_tutorials "Video tutorials")
  * **[Workbenches](/Workbenches "Workbenches"):** [Std Base](/Std_Base "Std Base"), [Assembly](/Assembly_Workbench "Assembly Workbench"), [BIM](/BIM_Workbench "BIM Workbench"), [CAM](/CAM_Workbench "CAM Workbench"), [Draft](/Draft_Workbench "Draft Workbench"), [FEM](/FEM_Workbench "FEM Workbench"), [Inspection](/Inspection_Workbench "Inspection Workbench"), [Material](/Material_Workbench "Material Workbench"), [Mesh](/Mesh_Workbench "Mesh Workbench"), [OpenSCAD](/OpenSCAD_Workbench "OpenSCAD Workbench"), [Part](/Part_Workbench "Part Workbench"), [PartDesign](/PartDesign_Workbench "PartDesign Workbench"), [Points](/Points_Workbench "Points Workbench"), [Reverse Engineering](/Reverse_Engineering_Workbench "Reverse Engineering Workbench"), [Robot](/Robot_Workbench "Robot Workbench"), Sketcher, [Spreadsheet](/Spreadsheet_Workbench "Spreadsheet Workbench"), [Surface](/Surface_Workbench "Surface Workbench"), [TechDraw](/TechDraw_Workbench "TechDraw Workbench"), [Test Framework](/Testing "Testing")

* * *

  * **[Addons](/Addon "Addon"):** [Addon Manager](/Std_AddonMgr "Std AddonMgr"), [External workbenches](/External_workbenches "External workbenches"), [Scripting and macros](/Scripting_and_macros "Scripting and macros")

* * *

  * **Hubs:** [User hub](/User_hub "User hub"), [Power users hub](/Power_users_hub "Power users hub"), [Developer hub](/Developer_hub "Developer hub")

