---
url: https://wiki.freecad.org/Spreadsheet_Workbench
title: Spreadsheet Workbench
scraped_at: 2025-09-08 16:44:30
---

Toggle the table of contents

## Contents

move to sidebar hide

  * Beginning
  * 1 Introduction
  * 2 Tools
  * 3 Preferences
  * 4 Removing cells can be dangerous
  * 5 Insert and remove rows and columns
  * 6 Edit cells
  * 7 Delete cells
  * 8 Cut and copy-paste cells
  * 9 Cell properties
  * 10 Cell expressions
  * 11 Interaction between spreadsheets and the CAD model Toggle Interaction between spreadsheets and the CAD model subsection
    * 11.1 References to CAD-data
    * 11.2 Spreadsheet data in expressions
    * 11.3 Complex models and recomputes
  * 12 Units
  * 13 Importing and exporting Toggle Importing and exporting subsection
    * 13.1 CSV format
    * 13.2 XLSX format
  * 14 Printing
  * 15 Current limitations
  * 16 Cell binding Toggle Cell binding subsection
    * 16.1 Create binding
    * 16.2 Change binding
    * 16.3 Remove binding
    * 16.4 Notes
  * 17 Configuration tables
  * 18 Scripting

# Spreadsheet Workbench

  * [Page](/Spreadsheet_Workbench "View the content page \[ctrl-option-c\]")
  * [Discussion](/Talk:Spreadsheet_Workbench "Discussion about the content page \[ctrl-option-t\]")

English

  * [Read](/Spreadsheet_Workbench)
  * [Edit](/index.php?title=Spreadsheet_Workbench&veaction=edit "Edit this page \[ctrl-option-v\]")
  * [Edit source](/index.php?title=Spreadsheet_Workbench&action=edit "Edit the source code of this page \[ctrl-option-e\]")
  * [Edit on GitHub](https://github.com/Reqrefusion/FreeCAD-Documentation-Project/blob/main/wiki/Spreadsheet_Workbench.wikitext "Edit this page on GitHub")
  * [View history](/index.php?title=Spreadsheet_Workbench&action=history "Past revisions of this page \[ctrl-option-h\]")

Tools

Tools

move to sidebar hide

Actions

  * [Read](/Spreadsheet_Workbench)
  * [Edit](/index.php?title=Spreadsheet_Workbench&veaction=edit "Edit this page \[ctrl-option-v\]")
  * [Edit source](/index.php?title=Spreadsheet_Workbench&action=edit "Edit the source code of this page \[ctrl-option-e\]")
  * [View history](/index.php?title=Spreadsheet_Workbench&action=history)

General

  * [What links here](/Special:WhatLinksHere/Spreadsheet_Workbench "A list of all wiki pages that link here \[ctrl-option-j\]")
  * [Related changes](/Special:RecentChangesLinked/Spreadsheet_Workbench "Recent changes in pages linked from this page \[ctrl-option-k\]")
  * [Special pages](/Special:SpecialPages "A list of all special pages \[ctrl-option-q\]")
  * [Permanent link](https://wiki.freecad.org/index.php?title=Spreadsheet_Workbench&oldid=1601614 "Permanent link to this revision of this page")
  * [Page information](/index.php?title=Spreadsheet_Workbench&action=info "More information about this page")
  * Expand all

Print/export

  * [Download as PDF](/index.php?title=Special:DownloadAsPdf&page=Spreadsheet_Workbench&action=show-download-screen)
  * [Printable version](javascript:print\(\); "Printable version of this page \[ctrl-option-p\]")

From FreeCAD Documentation

[Translate this page](/Special:Translate?group=page-
Spreadsheet+Workbench&action=page&filter=&language=en)This is the approved
revision of this page, as well as being the most recent.

Other languages:

  * [](/index.php?title=Special:Translate&group=page-Spreadsheet+Workbench&language=&task=view "Start translation for this language")
  * [Bahasa Indonesia](/Spreadsheet_Workbench/id "Spreadsheet Workbench \(1% translated\)")
  * [Deutsch](/Spreadsheet_Workbench/de "Arbeitsbereich Spreadsheet \(100% translated\)")
  * English
  * [Türkçe](/Spreadsheet_Workbench/tr "Hesap Tablosu Tezgahı \(1% translated\)")
  * [español](/Spreadsheet_Workbench/es "Entorno de trabajo Hoja de cálculo \(92% translated\)")
  * [français](/Spreadsheet_Workbench/fr "Atelier Spreadsheet \(100% translated\)")
  * [hrvatski](/Spreadsheet_Workbench/hr "Spreadsheet Workbench \(1% translated\)")
  * [italiano](/Spreadsheet_Workbench/it "Ambiente Spreadsheet \(100% translated\)")
  * [polski](/Spreadsheet_Workbench/pl "Środowisko pacy Arkusz Kalkulacyjny \(100% translated\)")
  * [português](/Spreadsheet_Workbench/pt "Bancada de Trabalho Folha de Cálculo \(1% translated\)")
  * [português do Brasil](/Spreadsheet_Workbench/pt-br "Bancada de trabalho Spreadsheet \(83% translated\)")
  * [română](/Spreadsheet_Workbench/ro "Atelierul Foi de calcul \(4% translated\)")
  * [svenska](/Spreadsheet_Workbench/sv "Spreadsheet Workbench/sv \(0% translated\)")
  * [čeština](/Spreadsheet_Workbench/cs "Spreadsheet Workbench \(1% translated\)")
  * [български](/Spreadsheet_Workbench/bg "Spreadsheet Workbench \(1% translated\)")
  * [русский](/Spreadsheet_Workbench/ru "Верстак Электронные Таблицы \(19% translated\)")
  * [українська](/Spreadsheet_Workbench/uk "Spreadsheet Workbench/uk \(1% translated\)")
  * [中文](/Spreadsheet_Workbench/zh "Spreadsheet Workbench/zh \(0% translated\)")
  * [中文（中国大陆）](/Spreadsheet_Workbench/zh-cn "电子表格工作台 \(4% translated\)")
  * [中文（臺灣）](/Spreadsheet_Workbench/zh-tw "Spreadsheet Workbench/zh-tw \(1% translated\)")
  * [日本語](/Spreadsheet_Workbench/ja "スプレッドシートワークベンチ \(9% translated\)")
  * [한국어](/Spreadsheet_Workbench/ko "스프레드시트 작업대 \(9% translated\)")

![](/images/6/6f/Arrow-left.svg) ![](/images/9/91/Workbench_Sketcher.svg)
[Sketcher Workbench](/Sketcher_Workbench "Sketcher Workbench")

![](/images/b/bf/Workbench_Surface.svg) [Surface Workbench](/Surface_Workbench
"Surface Workbench") ![](/images/a/af/Arrow-right.svg)

[Index](/Online_Help_Toc "Online Help Toc")
![](/images/7/76/Online_Help_Toc.svg)

[![](/images/b/be/Workbench_Spreadsheet.svg)](/index.php?title=File:Workbench_Spreadsheet.svg&filetimestamp=20240527155805&)Spreadsheet
workbench icon

## Introduction

The
[![](/images/b/be/Workbench_Spreadsheet.svg)](/index.php?title=File:Workbench_Spreadsheet.svg&filetimestamp=20240527155805&)
Spreadsheet Workbench allows you to create and edit spreadsheets, use data
from the spreadsheet as parameters in a model, fill the spreadsheet with data
retrieved from a model, perform calculations, and export the data to other
spreadsheet applications such as LibreOffice or Microsoft Excel.

[![](/images/thumb/2/25/Spreadsheet_screenshot.jpg/600px-
Spreadsheet_screenshot.jpg)](/index.php?title=File:Spreadsheet_screenshot.jpg&filetimestamp=20150215215445&)

A spreadsheet with certain cells filled with text and quantities

## Tools

  * [![](/images/f/f9/Spreadsheet_CreateSheet.svg)](/index.php?title=File:Spreadsheet_CreateSheet.svg&filetimestamp=20240527155333&) [Create sheet](/Spreadsheet_CreateSheet "Spreadsheet CreateSheet"): create a new spreadsheet.

  * [![](/images/b/be/Spreadsheet_Import.svg)](/index.php?title=File:Spreadsheet_Import.svg&filetimestamp=20240527155446&) [Import](/Spreadsheet_Import "Spreadsheet Import"): import a CSV file into a spreadsheet.

  * [![](/images/c/c5/Spreadsheet_Export.svg)](/index.php?title=File:Spreadsheet_Export.svg&filetimestamp=20240527155357&) [Export](/Spreadsheet_Export "Spreadsheet Export"): export a CSV file from a spreadsheet.

  * [![](/images/a/a1/Spreadsheet_MergeCells.svg)](/index.php?title=File:Spreadsheet_MergeCells.svg&filetimestamp=20240527155523&) [Merge cells](/Spreadsheet_MergeCells "Spreadsheet MergeCells"): merge selected cells.

  * [![](/images/b/bd/Spreadsheet_SplitCell.svg)](/index.php?title=File:Spreadsheet_SplitCell.svg&filetimestamp=20240527155619&) [Split cell](/Spreadsheet_SplitCell "Spreadsheet SplitCell"): split previously merged cells.

  * [![](/images/f/fa/Spreadsheet_AlignLeft.svg)](/index.php?title=File:Spreadsheet_AlignLeft.svg&filetimestamp=20240527154948&) [Align left](/Spreadsheet_AlignLeft "Spreadsheet AlignLeft"): align the contents of selected cells to the left.

  * [![](/images/9/9f/Spreadsheet_AlignCenter.svg)](/index.php?title=File:Spreadsheet_AlignCenter.svg&filetimestamp=20240527154915&) [Align center](/Spreadsheet_AlignCenter "Spreadsheet AlignCenter"): align the contents of selected cells to the center horizontally.

  * [![](/images/1/1c/Spreadsheet_AlignRight.svg)](/index.php?title=File:Spreadsheet_AlignRight.svg&filetimestamp=20240527155030&) [Align right](/Spreadsheet_AlignRight "Spreadsheet AlignRight"): align the contents of selected cells to the right.

  * [![](/images/6/67/Spreadsheet_AlignTop.svg)](/index.php?title=File:Spreadsheet_AlignTop.svg&filetimestamp=20240527155107&) [Align top](/Spreadsheet_AlignTop "Spreadsheet AlignTop"): align the contents of selected cells to the top.

  * [![](/images/d/d3/Spreadsheet_AlignVCenter.svg)](/index.php?title=File:Spreadsheet_AlignVCenter.svg&filetimestamp=20240527155205&) [Align vertical center](/Spreadsheet_AlignVCenter "Spreadsheet AlignVCenter"): align the contents of selected cells to the center vertically.

  * [![](/images/f/fe/Spreadsheet_AlignBottom.svg)](/index.php?title=File:Spreadsheet_AlignBottom.svg&filetimestamp=20240527154711&) [Align bottom](/Spreadsheet_AlignBottom "Spreadsheet AlignBottom"): top align the contents of selected cells to the bottom.

  * [![](/images/b/b7/Spreadsheet_StyleBold.svg)](/index.php?title=File:Spreadsheet_StyleBold.svg&filetimestamp=20240527155649&) [Style bold](/Spreadsheet_StyleBold "Spreadsheet StyleBold"): toggle the contents of selected cells to/from bold.

  * [![](/images/a/a6/Spreadsheet_StyleItalic.svg)](/index.php?title=File:Spreadsheet_StyleItalic.svg&filetimestamp=20240527155717&) [Style italic](/Spreadsheet_StyleItalic "Spreadsheet StyleItalic"): toggle the contents of selected cells to/from italic.

  * [![](/images/4/4b/Spreadsheet_StyleUnderline.svg)](/index.php?title=File:Spreadsheet_StyleUnderline.svg&filetimestamp=20240527155744&) [Style underline](/Spreadsheet_StyleUnderline "Spreadsheet StyleUnderline"): toggle the contents of selected cells to/from underlined.

  * [![](/images/5/5e/Spreadsheet_SetAlias.svg)](/index.php?title=File:Spreadsheet_SetAlias.svg&filetimestamp=20240527155548&) [Set alias](/Spreadsheet_SetAlias "Spreadsheet SetAlias"): set the alias for a selected cell.

  * Black and White set the foreground and the background colors of selected cells.

## Preferences

  * [![](/images/9/98/Preferences-spreadsheet.svg)](/index.php?title=File:Preferences-spreadsheet.svg&filetimestamp=20240522173746&) [Preferences](/Spreadsheet_Preferences "Spreadsheet Preferences"): the preferences for the Spreadsheet Workbench. [introduced in 0.20](/Release_notes_0.20 "Release notes 0.20")

## Removing cells can be dangerous

Note that deleting or removing cells with data can break the spreadsheet and
your model if it relies on the spreadheet. You are not prewarned if this
happens.

## Insert and remove rows and columns

Rows and columns can be inserted or removed by right-clicking a row or column
header and selecting the appropriate option from the contex menu. It is
possible to select multiple rows or columns first. Either by holding down the
Ctrl key while selecting the headers, or by holding down the left mouse button
and dragging.

## Edit cells

The content of a cell can be edited by selecting the cell and entering a value
in the **Content** inputbox at the top of the window. To edit a cell in-place,
select it and press F2, or double-click it.

## Delete cells

To delete one or more cells select them and press Del. This will delete their
contents, their properties and their aliases. To only delete the content of a
cell it should be edited instead.

## Cut and copy-paste cells

Cut and copy-paste operations can be used on spreadsheets cells. You can use
the normal shortcuts for these operations: Ctrl+X, Ctrl+C and Ctrl+V
respectively. To select multiple cells hold down the Ctrl key while selecting,
or hold down the left mouse button and drag to select a rectangular cell
range.

The cut and copy operations store the contents, properties and aliases of the
cells on the Clipboard. The paste operation writes the data in such a way that
the content of the top left cell of the stored data is dropped in the active
cell. Other stored content is placed relative to that cell. Formulas are
updated accordingly. Aliases are only pasted if they are unique.

## Cell properties

The properties of a spreadsheet cell can be edited by right-clicking the cell
and selecting **Properties...** from the context menu. The following dialog
pops up:

[![](/images/1/16/SpreadsheetCellPropDialog.png)](/index.php?title=File:SpreadsheetCellPropDialog.png&filetimestamp=20210403231228&)

As indicated by the tabs, the following properties can be changed:

  * Color: Text color and background color
  * Alignment: Text horizontal and vertical alignment
  * Style: Text style: bold, italic, underline
  * Units: Display units for this cell. Please read the Units section below.
  * Alias: Define an [alias](/Spreadsheet_SetAlias "Spreadsheet SetAlias") for this cell. This alias can be used in cell formulas and also in general [expressions](/Expressions "Expressions"); see section Spreadsheet data in expressions for more information.

## Cell expressions

A spreadsheet cell may contain a number, a text or an expression. Expressions
must start with an equal sign '='.

Cell expressions may contain numbers, functions, references to other cells,
and references to properties of the model (But see Current limitations below).
A cell can be referenced by its address (CAPITAL column letter + row number,
e.g. B4) or by its [alias](/Spreadsheet_SetAlias "Spreadsheet SetAlias").

**Note:** Cell expressions are treated by FreeCAD as programming code.
Therefore, when you edit a cell the content you see may not follow your
display settings:

  * The decimal separator is always a dot. But commas can also be used when entering values.
  * The number of displayed decimals can differ from your [preferences settings](/Preferences_Editor#Units "Preferences Editor").

References to objects in the model are explained under References to CAD-data
below. Using spreadsheet cell values to define model properties are explained
under Spreadsheet data in expressions below. For more information on
expressions and the available functions, see [Expressions](/Expressions
"Expressions").

## Interaction between spreadsheets and the CAD model

Data in the cells of a spreadsheet may be used in CAD model parameter
expressions. Thus, a spreadsheet may be used as the source for parameter
values used throughout a model, effectively gathering the values in one place.
When values are changed in the spreadsheet, they are propagated throughout the
model.

Similarly, properties from CAD model objects may be used in expressions in
spreadsheet cells. This allows use of object properties like volume or area in
the spreadsheet. If the name of an object in the CAD model is changed, the
change will automatically be propagated to any references in spreadsheet
expressions using the name which was changed.

More than one spreadsheet may be used in a document. A spreadsheet can be
identified using either its name or its label.

FreeCAD will automatically assign a unique name to a spreadsheet when it is
created. These names follow the pattern `Spreadsheet`, `Spreadsheet001`,
`Spreadsheet002` and so on. The name can not be changed, and it is not visible
in the properties of the spreadsheet. It can be used to refer to the
spreadsheet in an [Expression](/Expressions "Expressions") (see Spreadsheet
data in expressions below.)

The label of a spreadsheet is automatically set to the name of the spreadsheet
upon creation. Unlike the name, the label can be changed, for example in the
properties panel or using the context menu action Rename. By default FreeCAD
does not accept duplicate labels, but there is a
[preference](/Preferences_Editor#Document "Preferences Editor") to override
this. Spreadsheets with duplicate labels in the same document cannot be
referenced by their label.

FreeCAD checks for cyclic dependencies. See Current limitations.

### References to CAD-data

As indicated above, one can reference data from the CAD model in spreadsheet
expressions.

The following table shows some examples assuming the model has a feature named
"MyCube":

CAD-Data  | Cell in Spreadsheet  | Result   
---|---|---  
Parametric Length of a Part-Workbench Cube  | `=MyCube.Length` | Length with units mm   
Volume of the Cube  | `=MyCube.Shape.Volume` | Volume in mm³ without units   
Type of the Cube-shape  | `=MyCube.Shape.ShapeType` | String: Solid   
Label of the Cube  | `=MyCube.Label` | String: MyCube   
X coordinate of the center of mass of the Cube  | `=MyCube.Shape.CenterOfMass.x` | Coordinate in mm without units   
  
### Spreadsheet data in expressions

In order to use spreadsheet data in other parts of FreeCAD, you will usually
create an [Expression](/Expressions "Expressions") that refers to the
spreadsheet and the cell that contains the data you want to use. You can
identify spreadsheets by name or by label, and you can identify the cells by
address or by alias. Autocompletion is available for all forms of referencing.

| Spreadsheet by Name  | Spreadsheet by Label   
---|---|---  
Cell by Address  | `=Spreadsheet042.B5` | `=<<MySpreadsheet>>.B5`  
Cell by Alias  | `=Spreadsheet042.MyAlias` | `=<<MySpreadsheet>>.MyAlias`  
  
Expand

The recommended way to refer to spreadsheet data is to use the spreadsheet
label and cell alias name. For a more in-depth explanation of the pros and
cons of the referencing modes, see the expanded section below.

Using the spreadsheet label has the advantage that it can be freely changed to
describe the contents of the spreadsheet. It is also easier to identify the
spreadsheet that is being used since the text in the expression matches the
label shown in the model and property views. If you decide to change the label
of a spreadsheet, existing references to the contents of the spreadsheet will
be updated, so you won't break your expressions by renaming the spreadsheet.
The internal name of the spreadsheet is not readily available anywhere except
within the expression editor, so if you use the internal name and later decide
to rename the spreadsheets, you might have a hard time tracing your expression
data back to its source.

Be aware that when you create a new spreadsheet, the name and the label are
the same, so it is easy to accidentally use the spreadsheet name instead of
the label. A simple way to avoid this is to give the spreadsheet a meaningful
name before starting to use it in expressions.

While you may use the row and column number in an expression to reference a
cell, best practice is to give the cell an alias name and use that. See Cell
properties on how to set the alias. For example, if the data in cell B1
contained the length parameter for an object, an alias name of
`MyObject_Length` would allow the value to be referred to as
`<<MyParams>>.MyObject_Length` instead of `Spreadsheet.B1`. Besides being much
easier to read and understand, alias names are also much easier to change if
you decide to adjust the structure of your spreadsheet. Using an alias also
has the advantage that it is reasier to see which cells are used to control
other parts of the document. Note that FreeCAD will automatically adjust the
positional references in expressions if you insert or remove rows and columns
in the spreadsheet, so even if you use row and column numbers in an
expression, you can insert rows and columns without breaking the references to
the surrounding cells.

### Complex models and recomputes

Editing a spreadsheet will trigger a recompute of the 3D model, even if the
changes do not affect the model. For a complex model a recompute can take a
long time, and having to wait after every single edit is of course quite
annoying.

There are three solutions to deal with this:

  1. Temporarily skip recomputes: 
     * In the [Tree view](/Tree_view "Tree view") right-click the [![](/images/d/df/Document.svg)](/index.php?title=File:Document.svg&filetimestamp=20240522171432&) document that contains the spreadsheet.
     * Select the **Skip recomputes** option from the context menu.
     * There is a big disadvantage to this solution. New values entered in the spreadsheet will not be displayed until the document is recomputed. Instead `#PENDING` is shown.
     * You can either recompute manually, using the [Std Refresh](/Std_Refresh "Std Refresh") command, or disable **Skip recomputes** when you are done editing.
  2. Use a macro to automatically skip recomputes while editing a spreadsheet: 
     * Download and run [skipSheet.FCMacro](https://forum.freecad.org/viewtopic.php?f=8&t=48600#p419301).
     * This solution saves a few steps compared to the first solution, but also has the mentioned disadvantage.
  3. Put the spreadsheet in a separate [FreeCAD file](/File_Format_FCStd "File Format FCStd"): 
     * You can reference spreadsheet data from an external .FCStd file with this syntax: `=NameOfFile#<<MySpreadsheet>>.MyAlias`.
     * The advantage of having the spreadsheet in another file over switching off recomputes is that the spreadsheet itself does get recomputed.
     * The disadvantage is that the model won't automatically recompute after changes to the spreadsheet.
     * In the scenario where you first open the 'spreadsheet' file, change one or more values and then open the 'model' file, there won't be any indication that the model needs to be recomputed. But if both files are open the [Std Refresh](/Std_Refresh "Std Refresh") icon will update correctly for the 'model' file after changes to the 'spreadsheet' file.

## Units

The Spreadsheet has a notion of dimension (units) associated with cell values.
A number entered without an associated unit has no dimension. The unit should
be entered immediately following the number value, with no intervening space.
If a number has an associated unit, that unit will be used in all
calculations. For example, the multiplication of two lengths with the unit mm
gives an area with the unit mm².

If a cell contains a value which represents a dimension, it should be entered
with its associated unit. While in many simple cases one can get by with a
dimensionless value, it is unwise to not enter the unit. If a value
representing a dimension is entered without its associated unit, there are
some sequences of operations which cause FreeCAD to complain of incompatible
units in an expression when it appears the expression should be valid. (This
may be better understood by viewing [this
thread](https://forum.freecad.org/viewtopic.php?f=3&t=34713&p=292455#p292438)
in the FreeCAD forums.)

You can change the units displayed for a cell value using the Cell properties
dialog. This does not change the value contained in the cell; it only converts
the existing value for display. The value used for calculations does not
change, and the results of formulas using the value do not change. For
example, a cell containing the value "5.08cm" can be displayed as "2in" by
changing the units tab value to "in".

A dimensionless number cannot be changed to a number with a unit by the cell
properties dialog. One can put in a unit string, and that string will be
displayed; but the cell still contains a dimensionless number. In order to
change a dimensionless value to a value with a dimension, the value itself
must be re-entered with its associated unit.

Occasionally it may be desirable to get rid of a dimension in an expression.
This can be done by multiplying by 1 with a reciprocal unit.

## Importing and exporting

### CSV format

FreeCAD spreadsheets can be imported and exported to the
[CSV](https://en.wikipedia.org/wiki/Comma-separated_values) format which can
also be read and written by most other spreadsheet applications such as
Microsoft Excel or LibreOffice Calc. See [Spreadsheet
Import](/Spreadsheet_Import "Spreadsheet Import") and [Spreadsheet
Export](/Spreadsheet_Export "Spreadsheet Export") for more information.

### XLSX format

Spreadsheets in the Excel-format XLSX can be imported with the [Std
Import](/Std_Import "Std Import") command or the [Std Open](/Std_Open "Std
Open") command. The following features are supported:

  * All functions that are also available in the FreeCAD spreadsheet. Other functions give an error in the corresponding cell after import.
  * Alias names for cells.
  * More than one sheet in the Excel-spreadsheet. In this case one FreeCAD spreadsheet is created for each Excel sheet.

Other functionality is not imported into the FreeCAD spreadsheet.

## Printing

To handle the page setup necessary for printing, FreeCAD spreadsheets are
printed by inserting them into a [TechDraw Spreadsheet
View](/TechDraw_SpreadsheetView "TechDraw SpreadsheetView").

## Current limitations

FreeCAD checks for cyclic dependencies when it recomputes. By design, that
check stops at the level of the spreadsheet object. As a consequence, you
should not have a spreadsheet which contains both cells whose values are used
to specify parameters to the model, and cells whose values use output from the
model. For example, you cannot have cells specifying the length, width, and
height of an object, and another cell which references the total volume of the
resulting shape. This restriction can be surmounted by having two
spreadsheets: one used as a data-source for input parameters to the model and
the other used for calculations based on resultant geometry-data.

## Cell binding

[introduced in 0.20](/Release_notes_0.20 "Release notes 0.20")

It is possible to bind the content of cells to other spreadsheet cells. This
can be useful when dealing with large tables or to get cell content from
another spreadsheet.

### Create binding

To bind, for example, the cell range A3-C4 to the cell range B1-D2:

  1. Select the cell range A3-C4. 
  2. Right-click and select **Bind...** from the context menu. 
  3. The **Bind Spreadsheet Cells** dialog opens. 
  4. Set the range B1-D2 for the **To cells** :   
[![](/images/b/bc/Spreadsheet_binding-
dialog.png)](/index.php?title=File:Spreadsheet_binding-
dialog.png&filetimestamp=20220609000850&)

  5. Press OK. 
  6. Bound cells have a blue border to highlight the binding. 
  7. If you now enter something in cell C1, the same will immediately appear in cell B3. 

[![](/images/f/f5/Spreadsheet_binding-
result.png)](/index.php?title=File:Spreadsheet_binding-
result.png&filetimestamp=20220605224223&)

The spreadsheet may now look like this

### Change binding

  1. Right-click a bound cell (there is no need to highlight the whole bound range) and select **Bind...** from the context menu.
  2. The **Bind Spreadsheet Cells** dialog opens.
  3. Change one or more options. Note that the **Bind cells** , the bound cell range, cannot be changed.
  4. Press OK.

### Remove binding

  1. Right-click a bound cell (there is no need to highlight the whole bound range) and select **Bind...** from the context menu.
  2. The **Bind Spreadsheet Cells** dialog opens.
  3. Press Unbind.

### Notes

  * The **Hide dependency of binding** option can be used to prevent problems with cyclic dependencies between spreadsheets. Selecting it is necessary when, for example, cells in _Spreadsheet A_ are bound to _Spreadsheet B_ , while cells in _Spreadsheet B_ , in turn, are bound to some other cells in _Spreadsheet A_. This option should be used with caution: 
    * Hiding dependencies can be dangerous because broken dependencies can damage your FreeCAD file. For example, when you delete a spreadsheet you will not be warned about hidden dependencies.
    * When you open a document with a spreadsheet containing a hidden dependency, you will get the spreadsheet marked to be recomputed. This is because a cyclic dependency cannot be recomputed automatically. To recompute the [Std Refresh](/Std_Refresh "Std Refresh") tool must be used.
  * The cell binding has a range check and warns you about mismatched ranges. For example binding 1x3 cells to 3x2 cells cannot work because it is unknown which 3 cells of the original 6 cells should be used.
  * You cannot change the cell range of an existing binding. You must first unbind the cells and then create a new binding.
  * The frame color indicating the binding cannot be changed yet.

## Configuration tables

[introduced in 0.20](/Release_notes_0.20 "Release notes 0.20")

You can use Spreadsheets to create configuration tables with sets of
predefined parameters for your model, and then dynamically change which
configuration to use. See the [Configuration Tables](/Configuration_Tables
"Configuration Tables") tutorial. Read [this Forum
post](https://forum.freecad.org/viewtopic.php?f=17&t=42183) if you want to
know more about the inner workings of this feature.

## Scripting

    
    
    import Spreadsheet
    sheet = App.ActiveDocument.addObject("Spreadsheet::Sheet", "MySpreadsheet")
    sheet.Label = "Dimensions"
    
    sheet.set("A1", "10mm")
    sheet.recompute()
    sheet.get("A1")
    
    sheet.setAlias("B1", "Diameter")
    sheet.set("Diameter", "20mm")
    sheet.recompute()
    sheet.get("Diameter")
    
    # sheet.get() results in an error if the cell is empty.
    # sheet.getContents() can be used to check the cell first.
    if sheet.getContents("C1"):
        print(sheet.get("C1"))
    

  

![](/images/6/6f/Arrow-left.svg) ![](/images/9/91/Workbench_Sketcher.svg)
[Sketcher Workbench](/Sketcher_Workbench "Sketcher Workbench")

![](/images/b/bf/Workbench_Surface.svg) [Surface Workbench](/Surface_Workbench
"Surface Workbench") ![](/images/a/af/Arrow-right.svg)

[Index](/Online_Help_Toc "Online Help Toc")
![](/images/7/76/Online_Help_Toc.svg)

Expand[![](/images/b/be/Workbench_Spreadsheet.svg)](/index.php?title=File:Workbench_Spreadsheet.svg&filetimestamp=20240527155805&)
Spreadsheet

  * **Creation:** [Create sheet](/Spreadsheet_CreateSheet "Spreadsheet CreateSheet"), [Import](/Spreadsheet_Import "Spreadsheet Import"), [Export](/Spreadsheet_Export "Spreadsheet Export"), [Merge cells](/Spreadsheet_MergeCells "Spreadsheet MergeCells"), [Split cell](/Spreadsheet_SplitCell "Spreadsheet SplitCell"), [Set alias](/Spreadsheet_SetAlias "Spreadsheet SetAlias")
  * **Aligment:** [Align left](/Spreadsheet_AlignLeft "Spreadsheet AlignLeft"), [Align center](/Spreadsheet_AlignCenter "Spreadsheet AlignCenter"), [Align right](/Spreadsheet_AlignRight "Spreadsheet AlignRight"), [Align top](/Spreadsheet_AlignTop "Spreadsheet AlignTop"), [Align vertical center](/Spreadsheet_AlignVCenter "Spreadsheet AlignVCenter"), [Align bottom](/Spreadsheet_AlignBottom "Spreadsheet AlignBottom")
  * **Style:** [Style bold](/Spreadsheet_StyleBold "Spreadsheet StyleBold"), [Style italic](/Spreadsheet_StyleItalic "Spreadsheet StyleItalic"), [Style underline](/Spreadsheet_StyleUnderline "Spreadsheet StyleUnderline")

* * *

  * **Additional:** [Preferences](/Spreadsheet_Preferences "Spreadsheet Preferences")

Expand[![](/images/thumb/9/94/User_hub.png/24px-
User_hub.png)](/index.php?title=File:User_hub.png&filetimestamp=20190221145008&)
[User documentation](/User_hub "User hub")

  * **[Getting started](/Getting_started "Getting started")**
  * **Installation:** [Download](/Download "Download"), [Windows](/Installing_on_Windows "Installing on Windows"), [Linux](/Installing_on_Linux "Installing on Linux"), [Mac](/Installing_on_Mac "Installing on Mac"), [Additional components](/Installing_additional_components "Installing additional components"), [Docker](/Compile_on_Docker "Compile on Docker"), [AppImage](/AppImage "AppImage"), [Ubuntu Snap](/Ubuntu_Snap "Ubuntu Snap")
  * **Basics:** [About FreeCAD](/About_FreeCAD "About FreeCAD"), [Interface](/Interface "Interface"), [Mouse navigation](/Mouse_navigation "Mouse navigation"), [Selection methods](/Selection_methods "Selection methods"), [Object name](/Object_name "Object name"), [Preferences](/Preferences_Editor "Preferences Editor"), [Workbenches](/Workbenches "Workbenches"), [Document structure](/Document_structure "Document structure"), [Properties](/Property "Property"), [Help FreeCAD](/Help_FreeCAD "Help FreeCAD"), [Donate](/Donate "Donate")

* * *

  * **Help:** [Tutorials](/Tutorials "Tutorials"), [Video tutorials](/Video_tutorials "Video tutorials")
  * **[Workbenches](/Workbenches "Workbenches"):** [Std Base](/Std_Base "Std Base"), [Assembly](/Assembly_Workbench "Assembly Workbench"), [BIM](/BIM_Workbench "BIM Workbench"), [CAM](/CAM_Workbench "CAM Workbench"), [Draft](/Draft_Workbench "Draft Workbench"), [FEM](/FEM_Workbench "FEM Workbench"), [Inspection](/Inspection_Workbench "Inspection Workbench"), [Material](/Material_Workbench "Material Workbench"), [Mesh](/Mesh_Workbench "Mesh Workbench"), [OpenSCAD](/OpenSCAD_Workbench "OpenSCAD Workbench"), [Part](/Part_Workbench "Part Workbench"), [PartDesign](/PartDesign_Workbench "PartDesign Workbench"), [Points](/Points_Workbench "Points Workbench"), [Reverse Engineering](/Reverse_Engineering_Workbench "Reverse Engineering Workbench"), [Robot](/Robot_Workbench "Robot Workbench"), [Sketcher](/Sketcher_Workbench "Sketcher Workbench"), Spreadsheet, [Surface](/Surface_Workbench "Surface Workbench"), [TechDraw](/TechDraw_Workbench "TechDraw Workbench"), [Test Framework](/Testing "Testing")

* * *

  * **[Addons](/Addon "Addon"):** [Addon Manager](/Std_AddonMgr "Std AddonMgr"), [External workbenches](/External_workbenches "External workbenches"), [Scripting and macros](/Scripting_and_macros "Scripting and macros")

* * *

  * **Hubs:** [User hub](/User_hub "User hub"), [Power users hub](/Power_users_hub "Power users hub"), [Developer hub](/Developer_hub "Developer hub")

